name: docker

  # Disabled until needed
  # on: merge_group

env:
  TEST_TAG: cfpb/consumerfinancegov:test

jobs:

  zip_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.0
        id: filter
        with:
          filters: |
            docker:
              - 'docker/deployable-zipfile/Dockerfile'

      - name: Setup QEMU
        if: steps.filter.outputs.docker == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        if: steps.filter.outputs.docker == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build zipfile and export to Docker (not DockerHub)
        if: steps.filter.outputs.docker == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/deployable-zipfile/
          load: true
          tag: ${{ env.TEST_TAG }}
          build-args: FRONTEND_TARGET=production
