# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retirement_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='note',
            new_name='instructions_es',
        ),
    ]
