# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement_api', '0002_instructions_es_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='instructions_es',
            field=models.TextField(blank=True),
        ),
    ]
