# Generated by Django 3.2.13 on 2022-04-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing_instruction_guide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figcontentpage',
            name='footnotes',
        ),
        migrations.RemoveField(
            model_name='figcontentpage',
            name='process_report',
        ),
        migrations.RemoveField(
            model_name='figcontentpage',
            name='report_file',
        ),
    ]
