# Generated by Django 3.2.13 on 2022-04-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing_instruction_guide', '0002_auto_20220425_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figcontentpage',
            name='pdf_location',
        ),
    ]
