# Generated by Django 3.2.13 on 2022-04-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing_instruction_guide', '0003_remove_figcontentpage_pdf_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportsection',
            old_name='header',
            new_name='chapter_title',
        ),
        migrations.RemoveField(
            model_name='reportsection',
            name='is_appendix',
        ),
    ]
