# Generated by Django 3.2.13 on 2022-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing_instruction_guide', '0006_auto_20220425_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figcontentpage',
            name='report_type',
            field=models.CharField(blank=True, default='Filing Instruction Guide', max_length=100),
        ),
    ]
