# Generated by Django 3.2.13 on 2022-04-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing_instruction_guide', '0007_alter_figcontentpage_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figcontentpage',
            name='footnotes',
        ),
        migrations.RemoveField(
            model_name='figcontentpage',
            name='pdf_location',
        ),
        migrations.AlterField(
            model_name='figcontentpage',
            name='report_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
