# Generated by Django 3.2.24 on 2024-03-12 18:00

from django.db import migrations
import filing_instruction_guide.blocks
import v1.blocks
import wagtail.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('filing_instruction_guide', '0007_raw_html_affordances'),
    ]

    operations = [
        migrations.RunPython(code=migrations.RunPython.noop, reverse_code=migrations.RunPython.noop)
    ]
