# Generated by Django 3.2.15 on 2022-10-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing_instruction_guide', '0009_remove_datapoints_from_subsections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
