# Generated by Django 3.2.13 on 2022-04-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing_instruction_guide', '0011_auto_20220425_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figcontentpage',
            old_name='header',
            new_name='page_header',
        ),
        migrations.RenameField(
            model_name='reportsubsection',
            old_name='header',
            new_name='sub_section_title',
        ),
    ]
