# Generated by Django 3.2.23 on 2024-02-16 16:06

import django.contrib.postgres.indexes
from django.db import migrations, models
import tccp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tccp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cardsurveydata',
            name='targeted_credit_tiers_idx',
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='advance_apr_good',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='advance_apr_great',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='advance_apr_poor',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='balance_transfer_fees',
            field=tccp.fields.YesNoBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='intro_apr_good',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='intro_apr_great',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='intro_apr_poor',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='introductory_apr_offered',
            field=tccp.fields.YesNoBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='late_fees',
            field=tccp.fields.YesNoBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='purchase_apr_good',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='purchase_apr_great',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='purchase_apr_poor',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='secured_card',
            field=tccp.fields.YesNoBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='transfer_apr_good',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='transfer_apr_great',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='transfer_apr_poor',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cardsurveydata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['targeted_credit_tiers'], name='tccp_targeted_credit_tiers_idx', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='cardsurveydata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['rewards'], name='tccp_rewards_idx', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='cardsurveydata',
            index=models.Index(fields=['late_fees', 'late_fee_dollars'], name='tccp_late_fee_sorting_idx'),
        ),
    ]
