# Generated by Django 5.2.9 on 2026-02-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tccp", "0001_2024_squash"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CardSurveyData",
        ),
    ]
