# Generated by Django 3.2.23 on 2024-02-21 22:13

from django.db import migrations, models

from tccp.utils import get_card_slugifier


def populate_slugs(apps, schema_editor):
    CardSurveyData = apps.get_model("tccp", "CardSurveyData")
    slugify_card = get_card_slugifier()

    cards = CardSurveyData.objects.all()
    for card in cards:
        card.slug = slugify_card(card)

    CardSurveyData.objects.bulk_update(cards, ["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("tccp", "0002_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardsurveydata",
            name="slug",
            field=models.SlugField(max_length=255, default=""),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_slugs, migrations.RunPython.noop, elidable=True
        ),
    ]
