# Generated by Django 3.2.23 on 2024-02-26 21:32

from django.db import migrations, models
import tccp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tccp', '0004_slug_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsurveydata',
            name='late_fees',
            field=tccp.fields.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='product_name',
            field=models.TextField(db_index=True),
        ),
    ]
