# Generated by Django 3.2.23 on 2024-02-27 21:39

from django.db import migrations
import tccp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tccp', '0005_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsurveydata',
            name='introductory_apr_offered',
            field=tccp.fields.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='secured_card',
            field=tccp.fields.YesNoBooleanField(),
        ),
    ]
