# Generated by Django 3.2.24 on 2024-03-08 18:02

from django.db import migrations
import tccp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tccp', '0006_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsurveydata',
            name='top_25_institution',
            field=tccp.fields.YesNoBooleanField(db_index=True, default=False),
        ),
    ]
