# Generated by Django 3.2.24 on 2024-04-01 17:18

from django.db import migrations
import tccp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tccp', '0009_alter_cardsurveydata_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsurveydata',
            name='annual_fee',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='balance_transfer_fee_dollars',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='cash_advance_fee_dollars',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='foreign_transaction_fee_dollars',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='late_fee_dollars',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='late_fee_six_month_billing_cycle',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='maximum38',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='maximum58',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='minimum37',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='minimum57',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='minimum_balance_transfer_fee_amount',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='minimum_cash_advance_fee_amount',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='minimum_finance_charge_dollars',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='minimum_foreign_transaction_fee_amount',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='minimum_purchase_transaction_fee_amount',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='monthly_fee',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='other_fee_amount',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='other_fee_amount_2',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='other_fee_amount_3',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='other_fee_amount_4',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='other_fee_amount_5',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='other_periodic_fee_amount',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='over_limit_fee_dollars',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='periodic_max',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='periodic_min',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='purchase_transaction_fee_dollars',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardsurveydata',
            name='weekly_fee',
            field=tccp.fields.CurrencyDecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
