# Generated by Django 4.2.11 on 2024-04-17 18:21

from django.db import migrations
import tccp.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tccp", "0010_currencydecimalfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardsurveydata",
            name="targeted_credit_tiers",
            field=tccp.fields.JSONListField(
                choices=[
                    ("No credit score", "I don’t have a credit score"),
                    ("Credit score 619 or less", "619 or less"),
                    ("Credit scores from 620 to 719", "620-719"),
                    ("Credit score of 720 or greater", "720 and greater"),
                ],
                default=list,
            ),
        ),
    ]
