# Generated by Django 4.2.11 on 2024-05-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tccp", "0011_alter_cardsurveydata_targeted_credit_tiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardsurveydata",
            name="institution_type",
            field=models.TextField(
                blank=True, choices=[("Bank", "Bank"), ("CU", "CU")], null=True
            ),
        ),
    ]
