const usLayout = {
  AL: { label: 'Alabama', x: 6, y: 6 },
  AK: { label: 'Alaska', x: 1, y: 7 },
  AZ: { label: 'Arizona', x: 1, y: 5 },
  AR: { label: 'Arkansas', x: 4, y: 5 },
  CA: { label: 'California', x: 0, y: 4 },
  CO: { label: 'Colorado', x: 2, y: 4 },
  CT: { label: 'Connecticut', x: 9, y: 3 },
  DE: { label: 'Delaware', x: 9, y: 4 },
  DC: { label: 'District of Columbia', x: 8, y: 5 },
  FL: { label: 'Florida', x: 8, y: 7 },
  GA: { label: 'Georgia', x: 7, y: 6 },
  HI: { label: 'Hawaii', x: 0, y: 7 },
  ID: { label: 'Idaho', x: 1, y: 2 },
  IL: { label: 'Illinois', x: 5, y: 2 },
  IN: { label: 'Indiana', x: 5, y: 3 },
  IA: { label: 'Iowa', x: 4, y: 3 },
  KS: { label: 'Kansas', x: 3, y: 5 },
  KY: { label: 'Kentucky', x: 5, y: 4 },
  LA: { label: 'Louisiana', x: 4, y: 6 },
  ME: { label: 'Maine', x: 10, y: 0 },
  MD: { label: 'Maryland', x: 8, y: 4 },
  MA: { label: 'Massachusetts', x: 9, y: 2 },
  MI: { label: 'Michigan', x: 6, y: 2 },
  MN: { label: 'Minnesota', x: 4, y: 2 },
  MS: { label: 'Mississippi', x: 5, y: 6 },
  MO: { label: 'Missouri', x: 4, y: 4 },
  MT: { label: 'Montana', x: 2, y: 2 },
  NE: { label: 'Nebraska', x: 3, y: 4 },
  NV: { label: 'Nevada', x: 1, y: 3 },
  NH: { label: 'New Hampshire', x: 10, y: 1 },
  NJ: { label: 'New Jersey', x: 8, y: 3 },
  NM: { label: 'New Mexico', x: 2, y: 5 },
  NY: { label: 'New York', x: 8, y: 2 },
  NC: { label: 'North Carolina', x: 6, y: 5 },
  ND: { label: 'North Dakota', x: 3, y: 2 },
  OH: { label: 'Ohio', x: 6, y: 3 },
  OK: { label: 'Oklahoma', x: 3, y: 6 },
  OR: { label: 'Oregon', x: 0, y: 3 },
  PA: { label: 'Pennsylvania', x: 7, y: 3 },
  RI: { label: 'Rhode Island', x: 10, y: 3 },
  SC: { label: 'South Carolina', x: 7, y: 5 },
  SD: { label: 'South Dakota', x: 3, y: 3 },
  TN: { label: 'Tennessee', x: 5, y: 5 },
  TX: { label: 'Texas', x: 3, y: 7 },
  UT: { label: 'Utah', x: 1, y: 4 },
  VT: { label: 'Vermont', x: 9, y: 1 },
  VA: { label: 'Virginia', x: 7, y: 4 },
  WA: { label: 'Washington', x: 0, y: 2 },
  WV: { label: 'West Virginia', x: 6, y: 4 },
  WI: { label: 'Wisconsin', x: 5, y: 1 },
  WY: { label: 'Wyoming', x: 2, y: 3 },
};
export default usLayout;
