# This repo is used in ccdb5-ui.
approvedGitRepositories:
  - 'https://github.com/cfpb/cfpb-britecharts.git'

defaultSemverRangePrefix: ''

enableGlobalCache: false

enableMirror: true

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: '3d'

npmPreapprovedPackages:
  - '@cfpb/*'

# We need to cache binaries for different architectures
# so that GitHub Actions can find the binary for its platform.
supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
