nodeLinker: pnp
enableGlobalCache: false
cacheFolder: "./npm-packages-offline-cache"
enableTelemetry: false
enableHardenedMode: false
supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64
