# Docker Swarm compatible Compose file.  Intended for use
# with this repo's Jenkinsfile, not local development.
version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:2.4-alpine
    user: elasticsearch
    deploy:
      placement:
        constraints:
          - node.role!=manager
      restart_policy:
        condition: none
    networks:
      - app

  postgres:
    image: postgres:10-alpine
    user: postgres
    deploy:
      placement:
        constraints:
          - node.role!=manager
      restart_policy:
        condition: none
    environment:
      POSTGRES_USER: cfpb
      POSTGRES_PASSWORD_FILE: /var/run/secrets/PGPASSWORD
      POSTGRES_DB: cfgov
    ports:
      - 5432
    networks:
      - app
    secrets:
      - PGPASSWORD

  python:
    image: ${CFGOV_PYTHON_IMAGE}
    environment:
      ALLOW_ADMIN_URL: "True"
      APACHE_PORT: 8000
      APACHE_UPLOADS_F_ALIAS: /src/cfgov-refresh/cfgov/f/
      DATABASE_URL: postgres://cfpb@postgres/cfgov
      DJANGO_ADMIN_USERNAME: admin
      ES_HOST: elasticsearch
      GOVDELIVERY_BASE_URL: https://stage-api.govdelivery.com/
      GOVDELIVERY_ACCOUNT_CODE: USCFPB
      MEDIA_ROOT: /src/cfgov-refresh/cfgov/f/
      REFRESH_DB: ${REFRESH_DB}
      S3_ENABLED: "True"
    ports:
      - 8000
    networks:
      - app
      - lb
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_URL
      - CFGOV_PROD_DB_LOCATION
      - DJANGO_ADMIN_PASSWORD
      - GOVDELIVERY_USER
      - GOVDELIVERY_PASSWORD
      - PGPASSWORD
      - SECRET_KEY
    deploy:
      placement:
        constraints:
          - node.role!=manager
      restart_policy:
        condition: none
      labels:
        - com.docker.lb.hosts=${CFGOV_HOSTNAME}
        - com.docker.lb.port=8000
        - com.docker.lb.network=${LB_NETWORK}
    command: >
                bash -c "

                psql $${DATABASE_URL} -c 'SELECT COUNT(*) FROM auth_user'

                django_tables_exist=$$?

                if [ $$django_tables_exist -gt 0 ] || [ $$REFRESH_DB == 'true' ]; then
                    ./refresh-data.sh 
                    ./cfgov/manage.py update_index
                fi
                
                httpd -d cfgov/apache -D FOREGROUND"

networks:
  app:
  lb:
    name: ${LB_NETWORK}
    external: True

secrets:
  AWS_ACCESS_KEY_ID:
    name: aws_access_key
    external: True
  AWS_SECRET_ACCESS_KEY:
    name: aws_secret_key
    external: True
  AWS_STORAGE_BUCKET_NAME:
    name: aws_s3_storage_bucket_name
    external: True
  AWS_S3_URL:
    name: aws_s3_url
    external: True
  CFGOV_PROD_DB_LOCATION:
    name: cfgov_prod_db_location
    external: True
  DJANGO_ADMIN_PASSWORD:
    name: cfgov_django_admin_password
    external: True
  PGPASSWORD:
    name: cfgov_postgres_password
    external: True
  SECRET_KEY:
    name: cfgov_django_secret_key
    external: True
  GOVDELIVERY_USER:
    name: staging_govdelivery_user
    external: True
  GOVDELIVERY_PASSWORD:
    name: staging_govdelivery_password
    external: True
