services:
  python:
    build:
      target: dev
    ports:
      - "127.0.0.1:8000:8000" # Django
    volumes:
      - ./:/src/consumerfinance.gov/
      - ./extend-environment.sh:/etc/profile.d/extend-environment.sh
