{{- if .Values.mapping.enabled }}
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ include "cfgov.fullname" . }}-app
  labels:
    {{- include "cfgov.labels" . | nindent 4 }}
spec:
  ambassador_id:
    - "--apiVersion-v3alpha1-only--default"
  host: {{ .Values.mapping.app_host }}
  prefix: "/"
  service: {{ include "cfgov.fullname" . }}.cfgov:{{ .Values.service.port }}
  timeout_ms: 0
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ include "cfgov.fullname" . }}-s3
  labels:
    {{- include "cfgov.labels" . | nindent 4 }}
spec:
  ambassador_id:
    - "--apiVersion-v3alpha1-only--default"
  host: {{ .Values.mapping.files_host }}
  prefix: "/"
  service: "https://{{ .Values.mapping.files_bucket }}"
  timeout_ms: 0
  headers:
    Host: {{ .Values.mapping.files_bucket }}
{{- end }}
