# Generated by Django 3.2.20 on 2023-07-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('search', '0001_initial'), ('search', '0002_add_synonym_help_text')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(help_text='A comma-separated list of words that are synonyms', max_length=500)),
            ],
        ),
    ]
