# Generated by Django 3.2.12 on 2022-03-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('search', '0001_initial'),
        ('search', '0002_add_synonym_help_text'),
    ]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(help_text='A comma-separated list of words that are synonyms', max_length=500)),
            ],
        ),
    ]
