# Generated by Django 3.2.18 on 2023-05-04 14:42

from django.db import migrations, models

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    replaces = [('mega_menu', '0001_initial'), ('mega_menu', '0002_remove_featured_content'), ('mega_menu', '0003_additional_languages'), ('mega_menu', '0004_deprecate_zh_hans'), ('mega_menu', '0005_rename_chinese'), ('mega_menu', '0006_add_use_json_field_to_streamfields')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('zh-Hant', 'Chinese'), ('en', 'English'), ('ht', 'Haitian Creole'), ('ko', 'Korean'), ('ru', 'Russian'), ('es', 'Spanish'), ('tl', 'Tagalog'), ('vi', 'Vietnamese')], max_length=100, primary_key=True, serialize=False)),
                ('submenus', wagtail.fields.StreamField([('submenu', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('overview_page', wagtail.blocks.PageChooserBlock(required=False)), ('featured_links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(required=False)), ('url', wagtail.blocks.CharBlock(required=False))]), default=[])), ('other_links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(required=False)), ('url', wagtail.blocks.CharBlock(required=False)), ('icon', wagtail.blocks.CharBlock())]), default=[])), ('columns', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(required=False)), ('url', wagtail.blocks.CharBlock(required=False))]), default=[]))]), default=[]))]))], use_json_field=True)),
            ],
            options={
                'ordering': ('language',),
            },
        ),
    ]
