# Generated by Django 3.2.12 on 2022-03-08 22:00

from django.db import migrations, models

import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('mega_menu', '0001_initial'),
        ('mega_menu', '0002_remove_featured_content'),
    ]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=2, primary_key=True, serialize=False)),
                ('submenus', wagtail.core.fields.StreamField([('submenu', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('overview_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('featured_links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('text', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(required=False))]), default=[])), ('other_links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('text', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(required=False)), ('icon', wagtail.core.blocks.CharBlock())]), default=[])), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False)), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('text', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(required=False))]), default=[]))]), default=[]))]))])),
            ],
            options={
                'ordering': ('language',),
            },
        ),
    ]
