# Generated by Django 3.2.15 on 2023-01-30 20:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mega_menu', '0004_deprecate_zh_hans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='submenus',
            field=wagtail.fields.StreamField([('submenu', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('overview_page', wagtail.blocks.PageChooserBlock(required=False)), ('featured_links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(required=False)), ('url', wagtail.blocks.CharBlock(required=False))]), default=[])), ('other_links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(required=False)), ('url', wagtail.blocks.CharBlock(required=False)), ('icon', wagtail.blocks.CharBlock())]), default=[])), ('columns', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(required=False)), ('url', wagtail.blocks.CharBlock(required=False))]), default=[]))]), default=[]))]))], use_json_field=True),
        ),
    ]
