# Generated by Django 3.2.18 on 2023-05-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0003_petition_categories_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalDocsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Enter the URL for internal documentation.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal documentation",
            },
        ),
    ]
