# Generated by Django 3.2.19 on 2023-07-10 14:19

from django.db import migrations, models

import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_petition_categories_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgovimage',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width'),
        ),
        migrations.AlterField(
            model_name='cfgovrendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
