# Generated by Django 3.2.20 on 2023-08-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_internaldocssettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractfilterpage',
            name='preview_description',
        ),
        migrations.RemoveField(
            model_name='abstractfilterpage',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='abstractfilterpage',
            name='preview_subheading',
        ),
        migrations.RemoveField(
            model_name='abstractfilterpage',
            name='preview_title',
        ),
    ]
