# Generated by Django 3.2.23 on 2023-12-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_wagtail_image_field_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='flickr_url',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='speech_transcript',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='video_transcript',
        ),
    ]
