# Generated by Django 3.2.23 on 2023-12-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_event_page_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfgovpage',
            name='schema_json',
        ),
    ]
