# Generated by Django 3.2.23 on 2023-12-20 13:04

from django.db import migrations


# This is a one-off fix to convert an existing unique index on a Wagtail
# table into a unique constraint. See internal Design-and-Content-Team#389.
#
# https://github.com/wagtail/wagtail/blob/b6ba78de814f9bc293e55957ac70d890d950053e/wagtail/models/__init__.py#L3060
table_name = "wagtailcore_grouppagepermission"


index_name = "idx_17388_wagtailcore_grouppagepermission_group_id_16e761a17265"


# "nosec" is used here to suppress Bandit warning about this raw SQL.
# https://bandit.readthedocs.io/en/1.7.6/plugins/b608_hardcoded_sql_expressions.html
sql = f"""
DO $$ BEGIN
    IF EXISTS (SELECT FROM pg_indexes WHERE indexname='{index_name}') THEN
        DROP INDEX {index_name};
        ALTER TABLE {table_name} ADD CONSTRAINT {index_name} UNIQUE(group_id, page_id, permission_type);
    END IF;
END $$;
""".strip()  # nosec


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0014_update_ds_links"),
    ]

    operations = [
        migrations.RunSQL(sql, migrations.RunSQL.noop, elidable=True)
    ]
