# Generated by Django 3.2.23 on 2024-01-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_snippet_revisions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedResource',
        ),
    ]
