# Generated by Django 3.2.23 on 2024-01-10 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0017_remove_halfwidth"),
        ("v1", "0017_remove_relatedresource"),
    ]

    operations = []
