# Generated by Django 3.2.23 on 2024-01-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0004_ask_changes_202401'),
        ('v1', '0017_remove_halfwidth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedResource',
        ),
    ]
