# Generated by Django 3.2.23 on 2024-01-25 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0019_migrate_raw_anchors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcetag",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="resourcetag",
            name="tag",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="ResourceTag",
        ),
    ]
