# Generated by Django 3.2.23 on 2024-02-03 20:44

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0022_auto_20240201_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "info_unit_group",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "format",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("50-50", "50/50"),
                                            ("33-33-33", "33/33/33"),
                                            ("25-75", "25/75"),
                                        ],
                                        help_text="Choose the number and width of info unit columns.",
                                        label="Format",
                                    ),
                                ),
                                (
                                    "heading",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "level",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("h2", "H2"),
                                                        ("h3", "H3"),
                                                        ("h4", "H4"),
                                                        ("h5", "H5"),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "icon",
                                                wagtail.blocks.CharBlock(
                                                    help_text='Input the name of an icon to appear to the left of the heading. E.g., approved, help-round, etc. <a href="https://cfpb.github.io/design-system/foundation/iconography">See full list of icons</a>',
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "intro",
                                    wagtail.blocks.RichTextBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "link_image_and_heading",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Check this to link all images and headings to the URL of the first link in their unit's list, if there is a link.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "has_top_rule_line",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        help_text="Check this to add a horizontal rule line to top of info unit group.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "lines_between_items",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        help_text="Check this to show horizontal rule lines between info units.",
                                        label="Show rule lines between items",
                                        required=False,
                                    ),
                                ),
                                (
                                    "border_radius_image",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("none", "None"),
                                            ("rounded", "Rounded corners"),
                                            ("circle", "Circle"),
                                        ],
                                        help_text="Adds a <em>border-radius</em> class to images in this group, allowing for a rounded or circular border.",
                                        label="Border radius for images?",
                                        required=False,
                                    ),
                                ),
                                (
                                    "info_units",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "upload",
                                                                wagtail.images.blocks.ImageChooserBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                            (
                                                                "alt",
                                                                wagtail.blocks.CharBlock(
                                                                    help_text="No character limit, but be as succinct as possible. If the image is decorative (i.e., a screenreader wouldn't have anything useful to say about it), leave this field blank.",
                                                                    required=False,
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "heading",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "text",
                                                                wagtail.blocks.CharBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                            (
                                                                "level",
                                                                wagtail.blocks.ChoiceBlock(
                                                                    choices=[
                                                                        (
                                                                            "h2",
                                                                            "H2",
                                                                        ),
                                                                        (
                                                                            "h3",
                                                                            "H3",
                                                                        ),
                                                                        (
                                                                            "h4",
                                                                            "H4",
                                                                        ),
                                                                        (
                                                                            "h5",
                                                                            "H5",
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "icon",
                                                                wagtail.blocks.CharBlock(
                                                                    help_text='Input the name of an icon to appear to the left of the heading. E.g., approved, help-round, etc. <a href="https://cfpb.github.io/design-system/foundation/iconography">See full list of icons</a>',
                                                                    required=False,
                                                                ),
                                                            ),
                                                        ],
                                                        default={
                                                            "level": "h3"
                                                        },
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "body",
                                                    wagtail.blocks.RichTextBlock(
                                                        blank=True,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "links",
                                                    wagtail.blocks.ListBlock(
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "text",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "aria_label",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text='Add an ARIA label if the link text does not describe the destination of the link (e.g. has ambiguous text like "Learn more" that is not descriptive on its own).',
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "url",
                                                                    wagtail.blocks.CharBlock(
                                                                        default="/",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        default=[],
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "well",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        label="Well", required=False
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "feature_cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "feature_cards",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "category",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "text",
                                                                wagtail.blocks.CharBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                            (
                                                                "aria_label",
                                                                wagtail.blocks.CharBlock(
                                                                    help_text='Add an ARIA label if the link text does not describe the destination of the link (e.g. has ambiguous text like "Learn more" that is not descriptive on its own).',
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "url",
                                                                wagtail.blocks.CharBlock(
                                                                    default="/",
                                                                    required=False,
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "icon",
                                                    wagtail.blocks.TextBlock(),
                                                ),
                                                (
                                                    "footer_label",
                                                    wagtail.blocks.TextBlock(),
                                                ),
                                                (
                                                    "links",
                                                    wagtail.blocks.ListBlock(
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "text",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "aria_label",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text='Add an ARIA label if the link text does not describe the destination of the link (e.g. has ambiguous text like "Learn more" that is not descriptive on its own).',
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "url",
                                                                    wagtail.blocks.CharBlock(
                                                                        default="/",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        )
                                                    ),
                                                ),
                                            ]
                                        ),
                                        default=[],
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
