# Generated by Django 4.2.17 on 2025-04-16 21:03

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0023_alter_landingpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='notification',
            field=wagtail.fields.StreamField([('notification', 9)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('information', 'Information'), ('warning', 'Warning')]}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'The main notification message to display.', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Explanation text appears below the message in smaller type.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an ARIA label if the link text does not describe the destination of the link (e.g. has ambiguous text like "Learn more" that is not descriptive on its own).', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '/', 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 3), ('aria_label', 4), ('url', 5), ('is_link_boldface', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Links appear on their own lines below the explanation.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('type', 0), ('message', 1), ('explanation', 2), ('links', 8)]], {})}),
        ),
    ]
