# Generated by Django 3.2.24 on 2024-03-12 18:00

from django.db import migrations
import jobmanager.blocks
import v1.atomic_elements.tables
import v1.blocks
import v1.util.ref
import wagtail.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
import wagtailmedia.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0024_raw_html_affordances'),
    ]

    operations = [
        migrations.RunPython(code=migrations.RunPython.noop, reverse_code=migrations.RunPython.noop)
    ]
