# Generated by Django 5.1.14 on 2025-12-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0027_archived_rule_category"),
        ("v1", "0027_cfgovimage_description"),
    ]

    operations = []
