# Generated by Django 5.1.14 on 2025-11-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0027_archived_rule_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgovimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='description'),
        ),
    ]
