# Generated by Django 4.2.11 on 2024-04-29 12:46

from django.db import migrations

# This is a one-off fix to convert an existing unique index on a Wagtail
# table into a unique constraint. See internal Design-and-Content-Team#389
# for a description of the problem with a different constraint,
# https://github.com/cfpb/consumerfinance.gov/pull/8066 for the fix this is
# based on.
#
# The mode QueryDailyHits is and its `UNIQUE` constraints are removed in
# wagtail.search.migrations.0008_remove_query_and_querydailyhits_models.py
# in Wagtail 6.0. This migration will prepare our database for the constraint's
# constraint's removal.

table_name = "wagtailsearch_querydailyhits"
index_name = "idx_17496_wagtailsearch_querydailyhits_query_id_4e12c633921cb0c"
unique_together = "query_id, date"

# nosec used here to suppress Bandit warning about this raw SQL.
# https://bandit.readthedocs.io/en/latest/plugins/b608_hardcoded_sql_expressions.html
sql = f"""
DO $$ BEGIN
    IF EXISTS (SELECT FROM pg_indexes WHERE indexname='{index_name}') THEN
        DROP INDEX {index_name};
        ALTER TABLE {table_name} ADD CONSTRAINT {index_name} UNIQUE({unique_together});
    END IF;
END $$;
""".strip()  # nosec B608


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0032_alter_browsepage_content"),
    ]

    run_before = [
        ("wagtailsearch", "0008_remove_query_and_querydailyhits_models"),
    ]

    operations = [
        migrations.RunSQL(sql, migrations.RunSQL.noop, elidable=True)
    ]
