# Generated by Django 4.2.11 on 2024-05-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0033_wagtailsearch_querydailyhits_index_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reusabletext",
            name="sidefoot_heading",
            field=models.CharField(
                blank=True,
                help_text='Applies "slug" style heading. Only for use in sidebars and prefooters (the "sidefoot"). See https://cfpb.github.io/design-system/foundation/headings#slug-heading',
                max_length=255,
            ),
        ),
    ]
