# Generated by Django 4.2.16 on 2024-10-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0037_add_table_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='post_event_image',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='post_event_image_type',
        ),
    ]
