# Generated by Django 4.2.16 on 2024-10-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0038_emailsignup_disclaimer_page_set_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='post_event_image',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='post_event_image_type',
        ),
    ]
