# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 22:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0131_add-directors-notebook-category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='latest_updates',
            field=wagtail.wagtailcore.fields.StreamField([(b'posts', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'categories', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'speech-bubble', b'Blog'), (b'newspaper', b'Newsroom'), (b'document', b'Report'), (b'pencil', b"Director's notebook"), (b'date', b'Events'), (b'microphone', b'Speech'), (b'bullhorn', b'Press release'), (b'contract', b'Op-ed'), (b'double-quote', b'Testimony')], required=False)), (b'link', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.CharBlock(default=b'/', required=False))])), (b'date', wagtail.wagtailcore.blocks.DateTimeBlock(required=False))])))], blank=True),
        ),
    ]
