# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0134_simplify_filterable_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgovpagecategory',
            name='name',
            field=models.CharField(choices=[(b'Administrative adjudication docket', ((b'administrative-adjudication', b'Administrative adjudication'), (b'stipulation-and-constent-order', b'Stipulation and consent order'))), (b'Amicus Brief', ((b'us-supreme-court', b'U.S. Supreme Court'), (b'fed-circuit-court', b'Federal Circuit Court'), (b'fed-district-court', b'Federal District Court'), (b'state-court', b'State Court'))), (b'Blog', ((b'at-the-cfpb', b'At the CFPB'), (b'policy_compliance', b'Policy and compliance'), (b'data-research-reports', b'Data, research, and reports'), (b'info-for-consumers', b'Info for consumers'))), (b'Consumer Reporting Companies', ((b'nationwide', b'Nationwide'), (b'employment-screening', b'Employment screening'), (b'tenant-screening', b'Tenant screening'), (b'check-bank-screening', b'Check and bank screening'), (b'personal-property-insurance', b'Personal property insurance'), (b'medical', b'Medical'), (b'low-income-and-subprime', b'Low-income and subprime'), (b'supplementary-reports', b'Supplementary reports'), (b'utilities', b'Utilities'), (b'retail', b'Retail'), (b'gaming', b'Gaming'))), (b'Enforcement Action', ((b'fed-district-case', b'Federal district court case'), (b'administrative-adjudication-2', b'Administrative adjudication'), (b'stipulation-and-consent-order-2', b'Stipulation and consent order'))), (b'Final rule', ((b'interim-final-rule', b'Interim final rule'), (b'final-rule', b'Final rule'))), (b'FOIA Frequently Requested Record', ((b'report', b'Report'), (b'log', b'Log'), (b'record', b'Record'))), (b'Implementation Resource', ((b'compliance-aid', b'Compliance aid'), (b'official-guidance', b'Official guidance'))), (b'Newsroom', ((b'directors-notebook', b"Director's notebook"), (b'op-ed', b'Op-ed'), (b'press-release', b'Press release'), (b'speech', b'Speech'), (b'testimony', b'Testimony'))), (b'Notice and Opportunity for Comment', ((b'notice-proposed-rule', b'Advance notice of proposed rulemaking'), (b'proposed-rule', b'Proposed rule'), (b'interim-final-rule-2', b'Interim final rule'), (b'request-comment-info', b'Request for comment or information'), (b'proposed-policy', b'Proposed policy'), (b'intent-preempt-determ', b'Intent to make preemption determination'), (b'info-collect-activity', b'Information collection activities'), (b'notice-privacy-act', b'Notice related to Privacy Act'))), (b'Research Report', ((b'consumer-complaint', b'Consumer complaint'), (b'super-highlight', b'Supervisory Highlights'), (b'data-point', b'Data point'), (b'industry-markets', b'Industry and markets'), (b'consumer-edu-empower', b'Consumer education and empowerment'), (b'to-congress', b'To Congress'))), (b'Rule under development', ((b'notice-proposed-rule-2', b'Advance notice of proposed rulemaking'), (b'proposed-rule-2', b'Proposed rule'))), (b'Story', ((b'auto-loans', b'Auto loans'), (b'bank-accts-services', b'Bank accounts and services'), (b'credit-cards', b'Credit cards'), (b'credit-reports-scores', b'Credit reports and scores'), (b'debt-collection', b'Debt collection'), (b'money-transfers', b'Money transfers'), (b'mortgages', b'Mortgages'), (b'payday-loans', b'Payday loans'), (b'prepaid-cards', b'Prepaid cards'), (b'student-loans', b'Student loans')))], max_length=255),
        ),
    ]
