# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0139_rm_linkblob_and_imagetext_organisms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfgovpage',
            name='has_unshared_changes',
        ),
        migrations.RemoveField(
            model_name='cfgovpage',
            name='shared',
        ),
    ]
