# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('v1', '0148_relatedresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('heading_es', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'portal categories',
            },
        ),
        migrations.CreateModel(
            name='PortalCategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_portal_category', to='v1.PortalCategory')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v1_portalcategorytag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortalTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('heading_es', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortalTopicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_portal_topic', to='v1.PortalTopic')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v1_portaltopictag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portaltopic',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags are used to identify and organize portal topic pages.', through='v1.PortalTopicTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='portalcategory',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags are used to identify and organize portal see-all pages.', through='v1.PortalCategoryTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
