# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0149_rules_under_development'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageExcludedUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='v1.CFGOVPage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_updates', to='v1.HomePage')),
            ],
        ),
    ]
