# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-26 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0151_add_portal_tag_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='latest_updates',
        ),
    ]
