# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-08 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0152_remove_latest_updates_from_home_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AkamaiHistory',
            new_name='CDNHistory',
        ),
    ]
