# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0153_rename_akamaihistory_to_cdnhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='venue_coords',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
