# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0156_sublandingpage_portal_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedresource',
            name='text_es',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatedresource',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relatedresource',
            name='text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
