# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields
import wagtail.wagtailsearch.index


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0156_sublandingpage_portal_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('definition', wagtail.wagtailcore.fields.RichTextField()),
                ('anchor', models.CharField(blank=True, max_length=255, null=True)),
                ('term_es', models.CharField(blank=True, max_length=255, null=True)),
                ('definition_es', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('portal_topic', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='v1.PortalTopic')),
            ],
            bases=(wagtail.wagtailsearch.index.Indexed, models.Model),
        ),
    ]
