# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0158_add_language_fields_to_relatedresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpanishHomePage',
            fields=[
                ('homepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.HomePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('v1.homepage',),
        ),
    ]
