# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0162_add_videoplayer_to_blog_browse'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcategory',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Controls sequence of categories in sidebar navigation.'),
        ),
    ]
