# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0166_update_hero_labels_and_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='venue_zipcode',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
