# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0168_zipcode_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='venue_zip',
        ),
    ]
