# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0169_contact_phone_validators_and_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='venue_zip',
        ),
    ]
