# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-27 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0171_make_bureau_structure_download_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='venue_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='v1.CFGOVImage'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='venue_image_type',
            field=models.CharField(choices=[(b'map', b'Map'), (b'image', b'Image (selected below)'), (b'none', b'No map or image')], default=b'map', help_text=b'If "Image" is chosen here, you must select the image you want below. It should be sized to 1416x796.', max_length=8),
        ),
    ]
