# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0173_add_eventpage_persistent_body_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='post_event_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='v1.CFGOVImage'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='post_event_image_type',
            field=models.CharField(choices=[(b'placeholder', b'Placeholder image'), (b'image', b'Unique image (selected below)')], default=b'placeholder', help_text=b'Choose what to display after an event concludes. This will be overridden by embedded video if the "YouTube URL" field on the previous tab is populated. If "Unique image" is chosen here, you must select the image you want below. It should be sized to 1416x796.', max_length=16, verbose_name=b'Post-event image type'),
        ),
    ]
