# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-29 13:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0174_add_eventpage_post_event_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='live_stream_availability',
            field=models.BooleanField(default=False, help_text=b'Check if this event will be streamed live. This causes the event page to show the parts necessary for live streaming.', verbose_name=b'Streaming?'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='live_stream_date',
            field=models.DateTimeField(blank=True, help_text=b'Enter the date and time that the page should switch from showing the venue image to showing the live video feed. This is typically 15 minutes prior to the event start time.', null=True, verbose_name=b'Go Live Date'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='live_stream_url',
            field=models.URLField(blank=True, help_text=b'Format: https://www.youtube.com/embed/video_id. It can be obtained by clicking on Share > Embed on YouTube.', validators=[django.core.validators.RegexValidator(regex=b'^https?:\\/\\/www\\.youtube\\.com\\/embed\\/.*$')], verbose_name=b'URL'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text=b'Format: https://www.youtube.com/embed/video_id. It can be obtained by clicking on Share > Embed on YouTube.', validators=[django.core.validators.RegexValidator(regex=b'^https?:\\/\\/www\\.youtube\\.com\\/embed\\/.*$')], verbose_name=b'YouTube URL'),
        ),
    ]
