# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-18 14:21
from __future__ import unicode_literals

from django.db import migrations

from v1.util.migrations import migrate_page_types_and_fields


def migrate_individual_pages(page_or_revision, data):
    if data['topics']:
        data['topic_filtering'] = 'sort_by_frequency'
    else:
        data['topic_filtering'] = 'no_filter'
    return data

def forward(apps, schema_editor):
    page_types_and_fields = [
        ('v1', 'BrowseFilterablePage', 'content', 'filter_controls'),
        ('v1', 'SublandingFilterablePage', 'content', 'filter_controls'),
    ]
    migrate_page_types_and_fields(
        apps,
        page_types_and_fields,
        migrate_individual_pages
    )

class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0177_improved_topic_filtering_options'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
