# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-11 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0181_update_post_date_description_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'permissions': (('export_feedback', 'Can export feedback from the Wagtail admin'),)},
        ),
    ]
