# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0185_auto_20191028_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['heading']},
        ),
    ]
