# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-31 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0185_auto_20191028_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='start_dt',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 20, 16, 7, 700860, tzinfo=utc), verbose_name=b'Start'),
            preserve_default=False,
        ),
    ]
