# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-06 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0188_expandable_group_header_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='start_dt',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 15, 55, 44, 441650, tzinfo=utc), verbose_name=b'Start'),
            preserve_default=False,
        ),
    ]
