# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('v1', '0191_expandable_group_heading_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(help_text=b'45 characters maximum. Sentence case, unless proper noun.', max_length=45)),
                ('thumbnail_heading', models.CharField(blank=True, help_text=b'Shortened version of the heading, if needed (no more than 30 characters maximum, including spaces).', max_length=30, null=True)),
                ('text', models.CharField(help_text=b'140 characters maximum (including spaces).', max_length=140)),
                ('link_text', models.CharField(help_text=b'30 characters maximum (including spaces). Lead with a verb, and be specific.', max_length=30)),
                ('link_url', models.CharField(max_length=255, verbose_name=b'Link URL')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='v1.CFGOVImage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
