# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-05 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0191_expandable_group_heading_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(help_text=b'<a href="https://cfpb.github.io/design-system/foundation/iconography">See full list of icon names.</a>', max_length=64)),
                ('text', models.TextField(help_text=b'100 characters maximum (including spaces).', max_length=100)),
                ('link_text', models.CharField(help_text=b'25 characters maximum (including spaces).', max_length=25)),
                ('link_url', models.CharField(max_length=255, verbose_name=b'Link URL')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageCarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text=b'45 characters maximum (including spaces). Sentence case, unless proper noun.', max_length=45)),
                ('body', models.TextField(help_text=b'160 characters maximum (including spaces).', max_length=160)),
                ('link_text', models.CharField(help_text=b'35 characters maximum (including spaces). Lead with a verb, and be specific.', max_length=35)),
                ('link_url', models.CharField(max_length=255, verbose_name=b'Link URL')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='v1.CFGOVImage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageInfoUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text=b'35 characters maximum (including spaces). Sentence case, unless proper noun.', max_length=35)),
                ('body', models.TextField(help_text=b'140 characters maximum (including spaces).', max_length=140)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='v1.CFGOVImage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageInfoUnitLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(help_text=b'40 characters maximum (including spaces).', max_length=40)),
                ('url', models.CharField(max_length=255, verbose_name=b'URL')),
                ('info_unit', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='v1.HomePageInfoUnit')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='card_heading',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='homepageinfounit',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_units', to='v1.HomePage'),
        ),
        migrations.AddField(
            model_name='homepagecarouselitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='v1.HomePage'),
        ),
        migrations.AddField(
            model_name='homepagecard',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='v1.HomePage'),
        ),
    ]
