# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-09 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0192_new_homepage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageinfounit',
            options={'ordering': ['sort_order']},
        ),
    ]
