# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-12 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0194_english_homepage_cleanup'),
    ]

    # GlossaryTerm is moving from v1.models.snippets to
    # ask_cfpb.models.snippets. Because of this, this migration will first
    # change the table name to match the default tablename for the
    # ask_cfpb.GlossaryTerm model.
    database_operations = [migrations.AlterModelTable('GlossaryTerm', 'ask_cfpb_glossaryterm')]

    # Then for the purpose of migration state, we'll delete the v1.GlossaryTerm
    # model. An Ask CFPB migration will "create" the ask_cfpb.GlossaryTerm model
    # in migration state.
    state_operations = [migrations.DeleteModel('GlossaryTerm')]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations
      )
    ]
