# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0200_expandable_group_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgovimage',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
    ]
