# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-10 04:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0206_add_enforcement_action_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnforcementActionDocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='enforcementactionpage',
            name='docket_number',
        ),
        migrations.AddField(
            model_name='enforcementactiondocket',
            name='action',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='docket_numbers', to='v1.EnforcementActionPage'),
        ),
    ]
