# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0211_add_schema_blocks_to_blogpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='body_shown_in_expandables',
            field=models.BooleanField(default=False),
        ),
    ]
