# Generated by Django 3.2.13 on 2022-05-26 18:31

from functools import partial

from django.db import migrations

from v1.util.migrations import (
    convert_emailsignup_block_to_snippet,
    migrate_page_types_and_fields,
)


def forwards(apps, schema_editor):
    page_types_and_fields = [
        ('v1', 'CFGOVPage', 'sidefoot', 'email_signup'),
        ('v1', 'BlogPage', 'content', 'email_signup'),
        ('v1', 'LearnPage', 'content', 'email_signup'),
    ]
    migrate_page_types_and_fields(
        apps,
        page_types_and_fields,
        partial(convert_emailsignup_block_to_snippet, apps)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0212_emailsignup_snippet'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
