# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-20 15:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0214_add_campaignpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgovpage',
            name='schema_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Enter structured data for this page in JSON-LD format, for use by search engines in providing rich search results. <a href="https://developers.google.com/search/docs/guides/intro-structured-data">Learn more.</a> JSON entered here will be output in the <code>&lt;head&gt;</code> of the page between <code>&lt;script type="application/ld+json"&gt;</code> and <code>&lt;/script&gt;</code> tags.', null=True, verbose_name='Schema JSON'),
        ),
    ]
