# Generated by Django 2.2.12 on 2020-05-19 17:06

from django.db import migrations, models
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0216_add_title_to_howto_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgovpage',
            name='authors',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma separated list of authors.', related_name='authored_pages', through='v1.CFGOVAuthoredPages', to='taggit.Tag', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='cfgovpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='tagged_pages', through='v1.CFGOVTaggedPages', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='live_stream_availability',
            field=models.BooleanField(blank=True, default=False, help_text='Check if this event will be streamed live. This causes the event page to show the parts necessary for live streaming.', verbose_name='Streaming?'),
        ),
    ]
