# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-15 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0216_auto_20200515_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportsubsection',
            old_name='body',
            new_name='sub_body',
        ),
        migrations.RenameField(
            model_name='reportsubsection',
            old_name='subheader',
            new_name='sub_header',
        ),
        migrations.RenameField(
            model_name='reportsubsection',
            old_name='html_id',
            new_name='sub_id',
        ),
    ]
