# Generated by Django 3.2.15 on 2022-09-16 12:31

from django.db import migrations, models
import wagtail_editable_help.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0216_heading_block_h5s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsepage',
            name='share_and_print',
            field=models.BooleanField(default=False, help_text=wagtail_editable_help.models.HelpText('BrowsePage', 'share_and_print', default='Include share and print buttons above page content.')),
        ),
    ]
