# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0216_auto_20200429_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsectionssidenav',
            name='content',
        ),
        migrations.AddField(
            model_name='reportsectionssidenav',
            name='header',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reportsectionssidenav',
            name='pdf_location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='reportsectionssidenav',
            name='subheader',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportsectionssidenav',
            name='footnotes',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
