# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-18 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0216_add_title_to_howto_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgovpage',
            name='force_breadcrumbs',
            field=models.BooleanField(default=False, help_text="Normally breadcrumbs don't appear on pages one or two levels below the homepage. Check this option to force breadcrumbs to appear on all children of this page no matter how many levels below the homepage they are (for example, if you want breadcrumbs to appear on all children of a top-level campaign page).", verbose_name='Force breadcrumbs on child pages'),
        ),
    ]
