# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0217_auto_20200515_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection',
            name='is_appendix',
            field=models.BooleanField(default=False),
        ),
    ]
