# Generated by Django 2.2.12 on 2020-05-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0217_alter_taggit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgovpage',
            name='force_breadcrumbs',
            field=models.BooleanField(blank=True, default=False, help_text="Normally breadcrumbs don't appear on pages one or two levels below the homepage. Check this option to force breadcrumbs to appear on all children of this page no matter how many levels below the homepage they are (for example, if you want breadcrumbs to appear on all children of a top-level campaign page).", verbose_name='Force breadcrumbs on child pages'),
        ),
    ]
