# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0217_auto_20200505_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('html_id', models.CharField(blank=True, max_length=50)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='reportsection',
            old_name='section_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='reportsection',
            old_name='section_header',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='reportsection',
            old_name='section_id',
            new_name='html_id',
        ),
        migrations.AddField(
            model_name='reportsubsection',
            name='action',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_subsections', to='v1.ReportSection'),
        ),
    ]
