# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-29 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0218_reportsection_is_appendix'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='reportsectionssidenav',
            name='subheader',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='authornames',
            name='action',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_author_names', to='v1.ReportSectionsSidenav'),
        ),
    ]
