# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-29 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('v1', '0219_auto_20200528_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='authornames',
            name='bio_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page'),
        ),
    ]
