# Generated by Django 3.2.15 on 2022-10-14 15:09

from django.db import migrations


def forwards(apps, schema_editor):
    CFGOVPageCategory = apps.get_model("v1", "CFGOVPageCategory")
    for category in CFGOVPageCategory.objects.filter(name="policy_compliance"):
        category.name = "policy-compliance"
        category.save()


def backwards(apps, schema_editor):
    CFGOVPageCategory = apps.get_model("v1", "CFGOVPageCategory")
    for category in CFGOVPageCategory.objects.filter(name="policy-compliance"):
        category.name = "policy_compliance"
        category.save()


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0219_rename_policy_compliance_category"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
