# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-02 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0220_authornames_bio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsectionssidenav',
            name='report_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
