# Generated by Django 3.2.15 on 2023-01-19 02:40

from django.db import migrations, models


def migrate_zh_hans_to_zh_hant(apps, schema_editor):
    """Mark all Simplified Chinese pages as Traditional Chinese.

    We are deprecating the use of Simplified Chinese, but there may be some
    old pages in the Trash marked as that language. This data migration
    updates all of these pages to be Traditional Chinese instead.
    """
    CFGOVPage = apps.get_model("v1", "CFGOVPage")
    CFGOVPage.objects.select_for_update().filter(language="zh-Hans").update(
        language="zh-Hant"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0222_alter_cfgovpagecategory_name"),
    ]

    operations = [
        migrations.RunPython(migrate_zh_hans_to_zh_hant),
        migrations.AlterField(
            model_name="cfgovpage",
            name="language",
            field=models.CharField(
                choices=[
                    ("ar", "Arabic"),
                    ("zh-Hant", "Chinese (Traditional)"),
                    ("en", "English"),
                    ("ht", "Haitian Creole"),
                    ("ko", "Korean"),
                    ("ru", "Russian"),
                    ("es", "Spanish"),
                    ("tl", "Tagalog"),
                    ("vi", "Vietnamese"),
                ],
                default="en",
                max_length=100,
            ),
        ),
    ]
