# Generated by Django 3.2.15 on 2023-01-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("v1", "0223_deprecate_zh_hans"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfgovpage",
            name="english_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionally select the English version of this page (non-English pages only)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="non_english_pages",
                to="wagtailcore.page",
            ),
        ),
    ]
