# Generated by Django 3.2.15 on 2023-02-08 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0225_alter_cfgovpagecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedloginattempt',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='v1_failedloginattempt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordhistoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v1_passwordhistoryitem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temporarylockout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v1_temporarylockout', to=settings.AUTH_USER_MODEL),
        ),
    ]
