# Generated by Django 3.2.15 on 2023-02-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0226_prepare_login_models_to_move'),
        ('login', '0002_populate_login_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordhistoryitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='temporarylockout',
            name='user',
        ),
        migrations.DeleteModel(
            name='FailedLoginAttempt',
        ),
        migrations.DeleteModel(
            name='PasswordHistoryItem',
        ),
        migrations.DeleteModel(
            name='TemporaryLockout',
        ),
    ]
