# Generated by Django 3.2.15 on 2023-02-22 14:38

from django.db import migrations, models

import wagtail.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0227_remove_login_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgovpage',
            name='navigation_label',
            field=models.CharField(blank=True, help_text='Optional short label for left navigation.', max_length=100, null=True, verbose_name=wagtail.core.models.Page),
        ),
    ]
