# Generated by Django 2.2.13 on 2020-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0228_add_audio_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsepage',
            name='share_and_print',
            field=models.BooleanField(default=False, help_text='Include share and print buttons above page content.'),
        ),
    ]
