# Generated by Django 3.2.17 on 2023-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0229_contact_us_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgovpage',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('zh-Hant', 'Chinese'), ('en', 'English'), ('ht', 'Haitian Creole'), ('ko', 'Korean'), ('ru', 'Russian'), ('es', 'Spanish'), ('tl', 'Tagalog'), ('vi', 'Vietnamese')], default='en', max_length=100),
        ),
    ]
