# Generated by Django 2.2.16 on 2020-09-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0229_browsepage_share_and_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgovpage',
            name='archived_at',
            field=models.DateField(blank=True, null=True, verbose_name='Archive date'),
        ),
        migrations.AddField(
            model_name='cfgovpage',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Mark this page as archived'),
        ),
    ]
