# Generated by Django 3.2.17 on 2023-03-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0231_secondary_navigation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexedPageRevision',
        ),
    ]
