# Generated by Django 2.2.16 on 2020-09-24 19:20

from django.db import migrations

from v1.util.migrations import migrate_page_types_and_fields


def forward_mapper(page_or_revision, data):
    # Manipulate the stream block data forwards
    data['filter_children'] = False
    return data


def forwards(apps, schema_editor):
    page_types_and_fields = [
        ('v1', 'ActivityLogPage', 'content', 'filter_controls'),
        ('v1', 'NewsroomLandingPage', 'content', 'filter_controls'),
    ]
    migrate_page_types_and_fields(
        apps,
        page_types_and_fields,
        forward_mapper
    )

def backwards(apps, schema_editor):
    # There's nothing to do going backwards
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0231_add_filterable_list_filter_options'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
