# Generated by Django 3.2.17 on 2023-03-14 13:09
import logging

from django.db import migrations


logger = logging.getLogger(__name__)


def forwards(apps, schema_editor):
    Page = apps.get_model('wagtailcore', 'Page')
    PageRevision = apps.get_model('wagtailcore', 'PageRevision')

    orphaned_revisions = PageRevision.objects.exclude(
        page_id__in=Page.objects.values_list("pk", flat=True)
    )

    for pk, page_pk, content in orphaned_revisions.values_list(
        "pk", "page_id", "content"
    ):
        logger.info(
            f"Deleting orphaned page revision with pk {pk} "
            f"page pk {page_pk}, and path {content['url_path']}."
        )

    orphaned_revisions.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0067_alter_pagerevision_content_json'),
        ('v1', '0233_crc_tables'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
