# Generated by Django 2.2.16 on 2020-10-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0235_fix_is_archived_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgovpage',
            name='is_archived',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('never', 'Never')], default='no', help_text='If "Never" is selected, the page will not be archived automatically after a certain period of time.', max_length=16, verbose_name='This page is archived'),
        ),
    ]
