# Generated by Django 2.2.16 on 2020-11-19 17:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0238_auto_20201116_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enforcementactionpage',
            name='institution_type',
        ),
        migrations.AddField(
            model_name='enforcementactionpage',
            name='settled',
            field=models.BooleanField(blank=True, default=False, help_text='Check if settled, leave blank if contested.', verbose_name='Settled'),
        ),
        migrations.CreateModel(
            name='EnforcementActionInstitutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('Non-Bank', 'Nonbank'), ('Bank', 'Bank'), ('Individual', 'Individual')], max_length=50)),
                ('action', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_types', to='v1.EnforcementActionPage')),
            ],
        ),
    ]
