# Generated by Django 3.2.18 on 2023-05-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0238_collapse_oaa_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractfilterpage',
            name='comments_close_by',
        ),
        migrations.RemoveField(
            model_name='abstractfilterpage',
            name='date_filed',
        ),
    ]
