# Generated by Django 2.2.16 on 2020-12-10 01:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0239_remove_bureau_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enforcementactionpage',
            name='institution_type',
        ),
        migrations.RemoveField(
            model_name='enforcementactionpage',
            name='sidebar_header',
        ),
        migrations.CreateModel(
            name='EnforcementActionDisposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(blank=True, choices=[('expired-terminated-dismissed', 'Expired/Terminated/Dismissed'), ('pending-litigation', 'Pending Litigation'), ('post-order-post-judgment', 'Post Order/Post Judgment')], max_length=50)),
                ('institution_type', models.CharField(blank=True, choices=[('Non-Bank', 'Nonbank'), ('Bank', 'Bank'), ('Individual', 'Individual')], max_length=50)),
                ('total_consumer_relief', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('civil_money_penalties', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('date_filed', models.DateField(null=True)),
                ('final_order_date', models.DateField(blank=True, null=True)),
                ('dismissal_date', models.DateField(blank=True, null=True)),
                ('settled', models.BooleanField(blank=True, default=False, help_text='Check if settled, leave blank if contested.', verbose_name='Settled')),
                ('action', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='enforcement_dispositions', to='v1.EnforcementActionPage')),
            ],
        ),
    ]
