# Generated by Django 3.2.18 on 2023-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0239_field_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgovcontentowner',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
