# Generated by Django 2.2.16 on 2020-12-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0240_update_enforcement_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cfgovpagecategory',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='cfgovpagecategory',
            name='sort_order',
        ),
    ]
