# Generated by Django 3.2.18 on 2023-05-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0243_filterable_list_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractfilterpage',
            name='secondary_link_text',
        ),
        migrations.RemoveField(
            model_name='abstractfilterpage',
            name='secondary_link_url',
        ),
    ]
