# Generated by Django 2.2.16 on 2021-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0243_fcm_body_plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enforcementactionatrisk',
            name='at_risk_group',
            field=models.CharField(choices=[('Fair Lending', 'Fair Lending'), ('Limited English Proficiency', 'Limited English Proficiency'), ('Older Americans', 'Older Americans'), ('Servicemembers', 'Servicemembers'), ('Students', 'Students')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enforcementactionproduct',
            name='product',
            field=models.CharField(choices=[('Auto Finance Origination', 'Auto Finance Origination'), ('Auto Finance Servicing', 'Auto Finance Servicing'), ('Business Lending (ECOA)', 'Business Lending (ECOA)'), ('Consumer Reporting Agencies', 'Consumer Reporting Agencies'), ('Consumer Reporting ? User', 'Consumer Reporting - User'), ('Credit Cards', 'Credit Cards'), ('Credit Repair', 'Credit Repair'), ('Debt Collection', 'Debt Collection'), ('Debt Relief', 'Debt Relief'), ('Deposits', 'Deposits'), ('Furnishing', 'Furnishing'), ('Mortgage Origination', 'Mortgage Origination'), ('Mortgage Servicing', 'Mortgage Servicing'), ('Payments', 'Payments'), ('Prepaid', 'Prepaid'), ('Remittances', 'Remittances'), ('Short Term, Small Dollar', 'Short Term, Small Dollar'), ('Student Loan Origination', 'Student Loan Origination'), ('Student Loan Servicing', 'Student Loan Servicing'), ('Other Consumer Lending', 'Other Consumer Lending'), ('Other Consumer Products (Not Lending)', 'Other Consumer Product (not lending)')], max_length=50),
        ),
    ]
