# Generated by Django 3.2.19 on 2023-05-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0244_deprecate_2ndary_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsignup',
            name='url',
            field=models.URLField(blank=True, help_text='URL for the GovDelivery signup page people will be linked to in order to signup. Provide either this or the GovDelivery code, but not both.', null=True, verbose_name='GovDelivery URL'),
        ),
    ]
