# Generated by Django 2.2.16 on 2021-02-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0245_homepage_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageCarouselItem',
        ),
    ]
