# Generated by Django 3.2.19 on 2023-06-12 16:54

from django.db import migrations, models
import v1.atomic_elements.tables
import v1.blocks
import v1.util.ref
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0247_eap_no_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="browsefilterablepage",
            name="filter_children_only",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="browsefilterablepage",
            name="filtered_date_label",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="browsefilterablepage",
            name="filtered_ordering",
            field=models.CharField(
                choices=[
                    ("-start_date", "Date"),
                    ("title.raw", "Alphabetical"),
                ],
                default="-start_date",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="browsefilterablepage",
            name="show_filtered_categories",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="browsefilterablepage",
            name="show_filtered_dates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="browsefilterablepage",
            name="show_filtered_tags",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sublandingfilterablepage",
            name="filter_children_only",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sublandingfilterablepage",
            name="filtered_date_label",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="sublandingfilterablepage",
            name="filtered_ordering",
            field=models.CharField(
                choices=[
                    ("-start_date", "Date"),
                    ("title.raw", "Alphabetical"),
                ],
                default="-start_date",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sublandingfilterablepage",
            name="show_filtered_categories",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sublandingfilterablepage",
            name="show_filtered_dates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sublandingfilterablepage",
            name="show_filtered_tags",
            field=models.BooleanField(default=True),
        ),
    ]
