# Generated by Django 3.2.19 on 2023-06-09 16:37

from django.db import migrations

from v1.util.migrations import migrate_page_types_and_fields


def forwards(apps, schema_editor):
    page_types_and_fields = [
        ("v1", "BrowseFilterablePage", "content", ["filter_controls"]),
        ("v1", "SublandingFilterablePage", "content", ["filter_controls"]),
    ]
    migrate_page_types_and_fields(apps, page_types_and_fields, forward_mapper)


def forward_mapper(page_or_revision, data):
    data["filter_by_keyword"] = data.pop("title")
    data["filter_by_topics"] = data.pop("topics")
    data["filter_by_enforcement_statuses"] = data.pop("statuses", None)
    data["filter_by_enforcement_products"] = data.pop("products", None)
    data["filter_by_language"] = data.pop("language", None)
    data["filter_by_date_range"] = data.pop("date_range")

    categories = data.pop("categories")
    data["filter_by_category"] = categories.pop("filter_category")
    data["category_choices"] = categories.pop("page_type")

    return data


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0248_populate_filterable"),
    ]

    operations = [
        migrations.RunPython(forwards, elidable=True),
    ]
