# Generated by Django 3.2.20 on 2023-07-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailinventory', '0003_pageblock_id_bigautofield'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailcore', '0078_referenceindex'),
        ('v1', '0253_new_table_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignPage',
        ),
    ]
