# Generated by Django 2.2.16 on 2021-04-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0253_add_reusable_text_to_legacy_newsroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageCarouselItem',
        ),
    ]
