# Generated by Django 2.2.16 on 2021-04-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0253_add_reusable_text_to_legacy_newsroom'),
    ]

    run_before = [
        ('wagtailembeds', '0008_allow_long_urls'),
    ]

    # This is a temporary fix for an inconsistency between the expected state of
    # the wagtailembeds_embed table constrains and its actual state. This
    # manifests as a failure of the wagtailembeds_0008_allow_long_urls migration
    # to apply.
    #
    # Once this migration has successfully run, the RunSQL below will be
    # removed and this migration will become a noop.
    operations = [
        migrations.RunSQL('''
BEGIN;
DROP INDEX idx_17439_wagtailembeds_embed_url_37a13a49926a4846_uniq;
ALTER TABLE "wagtailembeds_embed" ADD CONSTRAINT "wagtailembeds_embed_url_max_width_8a2922d8_uniq" UNIQUE ("url", "max_width");
COMMIT;
        ''')
    ]
