# Generated by Django 2.2.23 on 2021-06-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0258_simple_chart_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgovpage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('zh', 'Chinese'), ('vi', 'Vietnamese'), ('ko', 'Korean'), ('tl', 'Tagalog'), ('ru', 'Russian'), ('ar', 'Arabic'), ('ht', 'Haitian Creole'), ('zh-Hans', 'Chinese (Simplified)')], default='en', max_length=7),
        ),
    ]
