# Generated by Django 2.2.23 on 2021-06-11 14:35

from django.db import migrations, models

def migrate_language_fn(from_lang, to_lang):
    def migrate_language(apps, schema_editor):
        CFGOVPage = apps.get_model('v1', 'CFGOVPage')
        CFGOVPage.objects.filter(language=from_lang).update(language=to_lang)
    return migrate_language

class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0259_add_simplified_chinese_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgovpage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('vi', 'Vietnamese'), ('ko', 'Korean'), ('tl', 'Tagalog'), ('ru', 'Russian'), ('ar', 'Arabic'), ('ht', 'Haitian Creole'), ('zh-Hans', 'Chinese (Simplified)'), ('zh-Hant', 'Chinese (Traditional)')], default='en', max_length=100),
        ),

        migrations.RunPython(
            migrate_language_fn('zh', 'zh-Hant'),
            migrate_language_fn('zh-Hant', 'zh'),
        ),
    ]
