# Generated by Django 2.2.23 on 2021-06-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0260_rename_chinese_lang_to_traditional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgovpage',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('zh-Hans', 'Chinese (Simplified)'), ('zh-Hant', 'Chinese (Traditional)'), ('en', 'English'), ('ht', 'Haitian Creole'), ('ko', 'Korean'), ('ru', 'Russian'), ('es', 'Spanish'), ('tl', 'Tagalog'), ('vi', 'Vietnamese')], default='en', max_length=100),
        ),
    ]
