# Generated by Django 2.2.24 on 2021-08-10 15:10

from django.db import migrations
import v1.atomic_elements.atoms
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0268_remove_category_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='answer_page_links',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.PageChooserBlock(page_type=['ask_cfpb.AnswerPage']))], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='highlight_cards',
            field=wagtail.core.fields.StreamField([('highlight', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock()), ('link_url', v1.atomic_elements.atoms.URLOrRelativeURLBlock())]))], blank=True),
        ),
    ]
