# Generated by Django 3.2.5 on 2022-02-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0273_django_32_update'),
        ('v1', '0276_consumer_advisories'),
    ]

    operations = [
    ]
