# Generated by Django 2.2.25 on 2022-02-14 19:28

from django.db import migrations

def forwards(apps, schema_editor):
    CFGOVPageCategory = apps.get_model('v1', 'CFGOVPageCategory')
    CFGOVPageCategory.objects.filter(name='official-guidance').delete()
    CFGOVPageCategory.objects.filter(name='compliance-aid').delete()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('v1', '0276_consumer_advisories'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
