# Generated by Django 2.2.25 on 2022-02-07 18:39

from django.db import migrations
import v1.atomic_elements.atoms
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0277_add_50_50_hero_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='highlight_cards',
            field=wagtail.core.fields.StreamField([('highlight', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock(required=False)), ('link_url', v1.atomic_elements.atoms.URLOrRelativeURLBlock())]))], blank=True),
        ),
    ]
