# Generated by Django 3.2.12 on 2022-02-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0277_merge_0273_django_32_update_0276_consumer_advisories'),
        ('v1', '0278_remove_unused_categories'),
    ]

    operations = [
    ]
