# Generated by Django 2.2.25 on 2022-02-24 20:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('v1', '0279_data_spotlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFGOVOwnedPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='v1.CFGOVPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v1_cfgovownedpages_items', to='taggit.Tag')),
            ],
            options={
                'verbose_name': 'Content Owner',
                'verbose_name_plural': 'Content Owners',
            },
        ),
        migrations.AddField(
            model_name='cfgovpage',
            name='content_owners',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma separated list of internal content owners.Listed names should use division acronyms.', related_name='owned_pages', through='v1.CFGOVOwnedPages', to='taggit.Tag', verbose_name='Content Owners'),
        ),
    ]
