# Generated by Django 2.2.27 on 2022-03-03 15:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0279_data_spotlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFGOVContentOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Content Owner',
                'verbose_name_plural': 'Content Owners',
            },
        ),
        migrations.CreateModel(
            name='CFGOVOwnedPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='v1.CFGOVPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_pages', to='v1.CFGOVContentOwner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cfgovpage',
            name='content_owners',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma separated list of internal content owners.Use division acronyms only.', related_name='cfgov_content_owners', through='v1.CFGOVOwnedPages', to='v1.CFGOVContentOwner', verbose_name='Content Owners'),
        ),
    ]
