# Generated by Django 3.2.12 on 2022-02-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0279_data_spotlight'),
        ('v1', '0279_merge_20220216_1353'),
    ]

    operations = [
    ]
