# Generated by Django 3.2.12 on 2022-03-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0283_removed_regs_gov_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageinfounit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepageinfounit',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepageinfounitlink',
            name='info_unit',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='answer_page_links',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlight_cards',
        ),
        migrations.DeleteModel(
            name='HomePageCard',
        ),
        migrations.DeleteModel(
            name='HomePageInfoUnit',
        ),
        migrations.DeleteModel(
            name='HomePageInfoUnitLink',
        ),
    ]
