# Generated by Django 3.2.20 on 2023-09-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailinventory', '0003_pageblock_id_bigautofield'),
        ('v1', '0008_deprecate_heading_related_posts_in_sidebar_breakout'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('paying_for_college', '0002_deprecate_iug_sharing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepayingStudentDebtPage',
        ),
    ]
