# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-19 08:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paying_for_college', '0003_expandable_group_heading_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='cohort_rank_control',
        ),
        migrations.RemoveField(
            model_name='school',
            name='cohort_rank_degrees',
        ),
        migrations.RemoveField(
            model_name='school',
            name='cohort_rank_state',
        ),
        migrations.AddField(
            model_name='school',
            name='cohort_ranking_by_control',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='cohort_ranking_by_highest_degree',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='cohort_ranking_by_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='program_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='program_most_popular',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='repay_5yr',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='GRADS WITH A DECLINING BALANCE AFTER 5 YRS', max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='default_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='LOAN DEFAULT RATE AT 5 YRS', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='median_total_debt',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='MEDIAN STUDENT DEBT 10 YRS AFTER ENROLLING', max_digits=7, null=True),
        ),
    ]
