# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-26 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paying_for_college', '0004_add_api_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='median_monthly_debt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MEDIAN STUDENT MONTHLY DEBT', max_digits=7, null=True),
        ),
    ]
