# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paying_for_college', '0009_expandable_group_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='median_monthly_debt',
            field=models.IntegerField(blank=True, help_text='MEDIAN MONTHLY PAYMENT FOR A 10-YEAR LOAN', null=True),
        ),
    ]
