# Generated by Django 2.0.13 on 2020-05-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paying_for_college', '0012_add_fields_for_intro_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='level_code',
            new_name='level_name',
        ),
    ]
