# Generated by Django 2.2.12 on 2020-06-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paying_for_college', '0012_add_fields_for_intro_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='level_code',
        ),
        migrations.AddField(
            model_name='program',
            name='level_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
