# Generated by Django 3.2.14 on 2022-07-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paying_for_college', '0014_convert_email_signups_blocks_to_snippets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
