# Generated by Django 2.2.24 on 2021-10-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0272_add_ask_search_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailinventory', '0001_initial'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('paying_for_college', '0022_add_ask_search_max_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentLoanQuizPage',
        ),
    ]
