# Generated by Django 3.2.5 on 2021-10-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paying_for_college', '0023_delete_studentloanquizpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='avg_net_price_slices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='cohort_ranking_by_control',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='cohort_ranking_by_highest_degree',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='cohort_ranking_by_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='main_campus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='online_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='program_most_popular',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
