# Generated by Django 3.2.5 on 2022-02-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paying_for_college', '0024_django_32_update'),
        ('paying_for_college', '0024_image_alt_no_limit'),
    ]

    operations = [
    ]
