# Generated by Django 3.2.13 on 2022-05-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0207_deprecate_feedback_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfgovpage',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='cfgovpage',
            name='is_archived',
        ),
    ]
