from six import StringIO

from django.core.management import call_command
from django.test import TestCase


class TestGenerateStreamFieldDocs(TestCase):
    def test_command_generates_output(self):
        out = StringIO()
        call_command('generate_streamfield_docs', stdout=out)
        output = out.getvalue()
        self.assertIn('Do not edit this file manually!', output)
        self.assertIn('# StreamField blocks', output)
