# Generated by Django 3.2.12 on 2022-03-14 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('prepaid_agreements', '0001_add_prepaid_models'), ('prepaid_agreements', '0002_add_deleted_at'), ('prepaid_agreements', '0003_order_prepaid_agreements_by_effective_date')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('issuer_name', models.CharField(blank=True, max_length=255)),
                ('prepaid_type', models.CharField(blank=True, max_length=255, null=True)),
                ('program_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('program_manager_exists', models.CharField(blank=True, max_length=255, null=True)),
                ('other_relevant_parties', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrepaidAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('compressed_files_url', models.TextField(blank=True, null=True)),
                ('bulk_download_path', models.TextField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='prepaid_agreements.prepaidproduct')),
            ],
            options={
                'ordering': ['-effective_date', '-created_time'],
            },
        ),
    ]
