# Generated by Django 3.2.23 on 2024-01-30 14:28

from django.db import migrations

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("regulations3k", "0005_update_ds_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulationpage",
            name="header",
            field=wagtail.fields.StreamField(
                [
                    (
                        "text_introduction",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "eyebrow",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional: Adds an H5 eyebrow above H1 heading text. Only use in conjunction with heading.",
                                        label="Pre-heading",
                                        required=False,
                                    ),
                                ),
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "intro",
                                    wagtail.blocks.RichTextBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "text",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "aria_label",
                                                    wagtail.blocks.CharBlock(
                                                        help_text='Add an ARIA label if the link text does not describe the destination of the link (e.g. has ambiguous text like "Learn more" that is not descriptive on its own).',
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "url",
                                                    wagtail.blocks.CharBlock(
                                                        default="/",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        required=False,
                                    ),
                                ),
                                (
                                    "has_rule",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Check this to add a horizontal rule line to bottom of text introduction.",
                                        label="Has bottom rule",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "notification",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("information", "Information"),
                                            ("warning", "Warning"),
                                        ]
                                    ),
                                ),
                                (
                                    "message",
                                    wagtail.blocks.CharBlock(
                                        help_text="The main notification message to display.",
                                        required=True,
                                    ),
                                ),
                                (
                                    "explanation",
                                    wagtail.blocks.TextBlock(
                                        help_text="Explanation text appears below the message in smaller type.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "text",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "aria_label",
                                                    wagtail.blocks.CharBlock(
                                                        help_text='Add an ARIA label if the link text does not describe the destination of the link (e.g. has ambiguous text like "Learn more" that is not descriptive on its own).',
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "url",
                                                    wagtail.blocks.CharBlock(
                                                        default="/",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        help_text="Links appear on their own lines below the explanation.",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
