# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations3k', '0024_add_standard_notification_regs_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='short_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
