# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 15:06
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Part = apps.get_model('regulations3k', 'Part')
    for part in Part.objects.all():
        part.short_name = 'Regulation ' + part.letter_code
        part.save()


def backwards(apps, schema_editor):
    Part = apps.get_model('regulations3k', 'Part')
    for part in Part.objects.all():
        if part.startswith('Regulation '):
            part.letter_code = part.short_name[11:]
        else:
            part.letter_code = ''
        part.save()


class Migration(migrations.Migration):

    dependencies = [
        ('regulations3k', '0025_part_short_name'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
