# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations3k', '0031_abstracthero_and_add_jumbohero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpart',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
