# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 14:07
from __future__ import unicode_literals

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations3k', '0032_require_label_on_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='label',
            field=models.CharField(help_text='Labels always require at least 1 alphanumeric character, then any number of alphanumeric characters and hyphens, with no spaces.', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[\\w]+[-\\w]*$', 32), 'Enter a valid “label” consisting of letters, numbers, hyphens, and no spaces.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='subpart',
            name='label',
            field=models.CharField(help_text='Labels always require at least 1 alphanumeric character, then any number of alphanumeric characters and hyphens, with no spaces.', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[\\w]+[-\\w]*$', 32), 'Enter a valid “label” consisting of letters, numbers, hyphens, and no spaces.', 'invalid')]),
        ),
    ]
