# Generated by Django 3.2.15 on 2022-09-16 12:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_editable_help.models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations3k', '0035_heading_block_h5s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulationpage',
            name='header',
            field=wagtail.core.fields.StreamField([('text_introduction', wagtail.core.blocks.StructBlock([('eyebrow', wagtail.core.blocks.CharBlock(help_text=wagtail_editable_help.models.HelpText('TextIntroduction', 'eyebrow', default='Optional: Adds an H5 eyebrow above H1 heading text. Only use in conjunction with heading.'), label='Pre-heading', required=False)), ('heading', wagtail.core.blocks.CharBlock(required=False)), ('intro', wagtail.core.blocks.RichTextBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=False)), ('aria_label', wagtail.core.blocks.CharBlock(help_text='Add an ARIA label if the link text does not describe the destination of the link (e.g. has ambiguous text like "Learn more" that is not descriptive on its own).', required=False)), ('url', wagtail.core.blocks.CharBlock(default='/', required=False))]), required=False)), ('has_rule', wagtail.core.blocks.BooleanBlock(help_text='Check this to add a horizontal rule line to bottom of text introduction.', label='Has bottom rule', required=False))]))], blank=True),
        ),
    ]
