# Generated by Django 3.2.18 on 2023-05-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0001_squashed_0047_add_use_json_field_to_streamfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpage',
            name='redirect_to_page',
        ),
    ]
