# Generated by Django 4.2.17 on 2025-01-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0001_2024_squash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpage',
            name='related_questions',
        ),
    ]
