# Generated by Django 3.2.18 on 2023-05-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0002_remove_answerpage_redirect_to_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpage',
            name='share_and_print',
        ),
    ]
