# Generated by Django 3.2.19 on 2023-06-08 14:43

import django.db.models.deletion
from django.db import migrations

import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0247_alter_cfgovcontentowner_slug'),
        ('ask_cfpb', '0003_remove_answerpage_share_and_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpage',
            name='portal_topic',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Limit to 1 portal topic if possible. If multiple topics are selected, the breadcrumb will either be the primary portal topic, if selected, or the Ask CFPB landing page if not.', to='v1.PortalTopic'),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='primary_portal_topic',
            field=modelcluster.fields.ParentalKey(blank=True, help_text='Use if more than one portal topic is checked, if one of those topics should be used as the page breadcrumb instead of the Ask CFPB landing page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_portal_topic', to='v1.portaltopic'),
        ),
    ]
