# Generated by Django 3.2.23 on 2024-01-10 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ask_cfpb", "0003_ask_changes_20240109"),
        ("ask_cfpb", "0003_remove_halfwidth"),
    ]

    operations = []
