# Generated by Django 4.2.16 on 2024-11-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ask_cfpb", "0009_add_table_caption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answerpage",
            name="related_questions",
        ),
    ]
