# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0016_modify_help_text_social_sharing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='answerpage',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='answerpage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='answerpage',
            name='last_edited',
            field=models.DateField(blank=True, help_text='Change the date to today if you make a significant change.', null=True),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='search_tags',
            field=models.CharField(blank=True, help_text="PLEASE DON'T USE. THIS FIELD IS NOT YET ACTIVATED.", max_length=1000),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='statement',
            field=models.TextField(blank=True, help_text='(Optional) Use this field to rephrase the question title as a statement. Use only if this answer has been chosen to appear on a money topic portal (e.g. /consumer-tools/debt-collection).'),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='answer',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='snippet',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Optional answer intro'),
        ),
    ]
