# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 00:01
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0017_adjust_fields_for_editing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpage',
            name='answer',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Do not use H2 or H3 to style text. Only use the HTML Editor for troubleshooting. To style tips, warnings and notes, select the content that will go inside the rule lines (so, title + paragraph) and click the Pencil button to style it. Re-select the content and click the button again to unstyle the tip.'),
        ),
    ]
