# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-27 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0144_relatedresource'),
        ('ask_cfpb', '0020_rm_formfieldwithbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpage',
            name='answer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Categorize this answer. Avoid putting into more than one category.', to='ask_cfpb.Category'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check to make this one of two featured answers on the landing page.'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='featured_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='redirect_to_page',
            field=models.ForeignKey(blank=True, help_text='Choose another AnswerPage to redirect this page to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirect_to_pages', to='ask_cfpb.AnswerPage'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='related_questions',
            field=models.ManyToManyField(blank=True, help_text='Maximum of 3', related_name='related_question', to='ask_cfpb.AnswerPage'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='related_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.RelatedResource'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='subcategory',
            field=models.ManyToManyField(blank=True, help_text='Choose only subcategories that belong to one of the categories checked above.', to='ask_cfpb.SubCategory'),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='search_tags',
            field=models.CharField(blank=True, help_text='Search words or phrases, separated by commas', max_length=1000),
        ),
    ]
