# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 06:33
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0021_add_remaining_answer_fields_to_answer_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpage',
            name='related_questions',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Maximum of 3', related_name='related_question', to='ask_cfpb.AnswerPage'),
        ),
    ]
