# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0022_add_remaining_answer_fields_to_answer_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerpage',
            old_name='snippet',
            new_name='short_answer',
        ),
        migrations.RenameField(
            model_name='answerpage',
            old_name='content',
            new_name='user_feedback',
        ),
    ]
