# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0022_add_remaining_answer_fields_to_answer_page'),
        ('v1', '0148_add_portal_tag_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpage',
            name='related_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.RelatedResource'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='subcategory',
            field=models.ManyToManyField(blank=True, help_text='Choose only subcategories that belong to one of the categories checked above.', to='ask_cfpb.SubCategory'),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='search_tags',
            field=models.CharField(blank=True, help_text='Search words or phrases, separated by commas', max_length=1000),
        ),
    ]
