# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('v1', '0151_add_portal_tag_models'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailinventory', '0001_initial'),
        ('ask_cfpb', '0024_add_portal_links_to_answerpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeraudiencepage',
            name='ask_audience',
        ),
        migrations.RemoveField(
            model_name='answeraudiencepage',
            name='cfgovpage_ptr',
        ),
        migrations.DeleteModel(
            name='AnswerAudiencePage',
        ),
    ]
