# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0025_remove_answer_audience_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpage',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='answerpage',
            name='redirect_to',
        ),
    ]
