# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 21:46
from __future__ import unicode_literals

import ask_cfpb.models.pages
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.wagtailroutablepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0153_rename_akamaihistory_to_cdnhistory'),
        ('ask_cfpb', '0026_remove_redirect_to_and_answer_id_from_answer_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSearchPage',
            fields=[
                ('cfgovpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.CFGOVPage')),
                ('overview', models.TextField(blank=True)),
                ('portal_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.PortalTopic')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin, ask_cfpb.models.pages.SecondaryNavigationJSMixin, 'v1.cfgovpage'),
        ),
    ]
