# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-11 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0033_add_article_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerresultspage',
            name='content',
        ),
    ]
