# Generated by Django 3.2.13 on 2022-05-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0039_2022_squash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpage',
            name='user_feedback',
        ),
    ]
