# Generated by Django 3.2.13 on 2022-05-26 18:31

from functools import partial

from django.db import migrations

from v1.util.migrations import (
    convert_emailsignup_block_to_snippet,
    migrate_page_types_and_fields,
)


def forwards(apps, schema_editor):
    page_types_and_fields = [
        ('ask_cfpb', 'AnswerPage', 'sidebar', 'email_signup'),
        ('ask_cfpb', 'ArticlePage', 'sidebar', 'email_signup'),
    ]
    migrate_page_types_and_fields(
        apps,
        page_types_and_fields,
        partial(convert_emailsignup_block_to_snippet, apps)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0041_emailsignup_snippet'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
