# Generated by Django 2.2.16 on 2020-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0041_answerpage_share_and_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpage',
            name='share_and_print',
            field=models.BooleanField(default=False, help_text='Include share and print buttons above answer.'),
        ),
    ]
