# Generated by Django 3.2.18 on 2023-03-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailinventory', '0003_pageblock_id_bigautofield'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('v1', '0234_clean_orphaned_revisions'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('ask_cfpb', '0045_set_max_num_on_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='cfgovpage_ptr',
        ),
        migrations.DeleteModel(
            name='ArticleLink',
        ),
        migrations.DeleteModel(
            name='ArticlePage',
        ),
    ]
