# Generated by Django 3.2.12 on 2022-03-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('ask_cfpb', '0001_initial'),
        ('ask_cfpb', '0002_answeraudiencepage'),
        ('ask_cfpb', '0003_add_answercategorypage'),
        ('ask_cfpb', '0004_add_ask_category_images'),
        ('ask_cfpb', '0005_delete_answertagproxy'),
        ('ask_cfpb', '0006_update_help_text'),
        ('ask_cfpb', '0007_subcategory_prefixes'),
        ('ask_cfpb', '0008_fix_verbose_name_plural'),
        ('ask_cfpb', '0009_update_social_image_help_text'),
        ('ask_cfpb', '0010_answerpage_sidebar'),
        ('ask_cfpb', '0011_move_reusable_text_chooser_block'),
        ('ask_cfpb', '0012_add_rule_option_to_module'),
        ('ask_cfpb', '0013_recreated'),
        ('ask_cfpb', '0014_recreated_2'),
        ('ask_cfpb', '0015_update_email_signup_options'),
        ('ask_cfpb', '0016_modify_help_text_social_sharing_image'),
        ('ask_cfpb', '0017_adjust_fields_for_editing'),
        ('ask_cfpb', '0018_migrate_answer_field_help_text'),
        ('ask_cfpb', '0019_add_disclaimer_pagechooserblock_to_emailsignup'),
        ('ask_cfpb', '0020_rm_formfieldwithbutton'),
        ('ask_cfpb', '0021_rssfeed_improvements'),
        ('ask_cfpb', '0022_add_remaining_answer_fields_to_answer_page'),
        ('ask_cfpb', '0023_rename_snippet_to_short_answer'),
        ('ask_cfpb', '0024_add_portal_links_to_answerpage'),
        ('ask_cfpb', '0025_remove_answer_audience_page'),
        ('ask_cfpb', '0026_remove_redirect_to_and_answer_id_from_answer_page'),
        ('ask_cfpb', '0027_portalsearchpage'),
        ('ask_cfpb', '0028_answerpage_answer_content'),
        ('ask_cfpb', '0029_answer_schema_blocks'),
        ('ask_cfpb', '0030_remove_answer_category_page'),
        ('ask_cfpb', '0031_remove_deprecated_models_and_fields'),
        ('ask_cfpb', '0032_remove_html_editor'),
        ('ask_cfpb', '0033_add_article_page'),
        ('ask_cfpb', '0034_remove_answerresultspage_content'),
        ('ask_cfpb', '0035_move_glossaryterm'),
        ('ask_cfpb', '0036_auto_20191219_1445'),
        ('ask_cfpb', '0037_recreated'),
        ('ask_cfpb', '0038_recreated2'),
        ('ask_cfpb', '0039_add_title_to_howto_block'),
        ('ask_cfpb', '0040_video_player'),
        ('ask_cfpb', '0041_answerpage_share_and_print'),
        ('ask_cfpb', '0042_share_and_print_help'),
        ('ask_cfpb', '0043_answerpage_notification'),
        ('ask_cfpb', '0044_add_aria_label_to_hyperlinks'),
        ('ask_cfpb', '0045_remove_category_sidebar'),
    ]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
