# Generated by Django 3.2.12 on 2022-03-08 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('agreements', '0001_initial'),
        ('agreements', '0002_auto_20160524_1806'),
        ('agreements', '0003_auto_20160608_1533'),
        ('agreements', '0004_auto_20160615_1814'),
        ('agreements', '0005_recreated'),
    ]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('slug', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(max_length=500)),
                ('size', models.IntegerField()),
                ('uri', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.issuer')),
            ],
        ),
    ]
