# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-05 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_recreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('salesforce_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prepaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('other_relevant_parties', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('issuer_name', models.CharField(blank=True, max_length=255)),
                ('program_type', models.CharField(blank=True, max_length=255)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('program_manager', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
