# Generated by Django 2.2.13 on 2020-07-22 14:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('v1', '0226_update_enforcement_action_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=200)),
                ('is_appendix', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchReportPage',
            fields=[
                ('cfgovpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.CFGOVPage')),
                ('process_report', models.BooleanField(default=False, help_text='If this is checked, when you press "save", the system will read in the report document and use its contents to overwrite the fields in the "Report Content" tab.<ul class="help">    <li>&bull; If you uploaded a new report file for processing, check this box.</li>    <li>&bull; If you manually edited fields in the "Report Content" tab, do not check this box</li></ul>')),
                ('report_type', models.CharField(blank=True, max_length=100)),
                ('header', models.CharField(blank=True, max_length=200)),
                ('subheader', models.TextField(blank=True)),
                ('pdf_location', models.CharField(blank=True, max_length=150)),
                ('footnotes', models.TextField(blank=True)),
                ('report_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'abstract': False,
            },
            bases=('v1.cfgovpage',),
        ),
        migrations.CreateModel(
            name='ReportSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_header', models.CharField(max_length=200)),
                ('sub_body', models.TextField(blank=True)),
                ('section', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_subsections', to='research_reports.ReportSection')),
            ],
        ),
        migrations.AddField(
            model_name='reportsection',
            name='report',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sections', to='research_reports.ResearchReportPage'),
        ),
        migrations.CreateModel(
            name='ReportAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('report', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_authors', to='research_reports.ResearchReportPage')),
            ],
        ),
    ]
