# Generated by Django 2.2.12 on 2020-06-05 03:31

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1', '0219_move_directors_notebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('cfgovpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.CFGOVPage')),
                ('report_type', models.CharField(default='', max_length=100)),
                ('header', models.CharField(default='', max_length=200)),
                ('subheader', models.TextField(blank=True)),
                ('pdf_location', models.CharField(default='', max_length=150)),
                ('footnotes', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('v1.cfgovpage',),
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=200)),
                ('html_id', models.CharField(blank=True, max_length=50)),
                ('is_appendix', models.BooleanField(default=False)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('action', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sections', to='research_reports.Report')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_header', models.CharField(max_length=200)),
                ('sub_id', models.CharField(blank=True, max_length=50)),
                ('sub_body', wagtail.core.fields.RichTextField(blank=True)),
                ('action', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_subsections', to='research_reports.ReportSection')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('action', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_author_names', to='research_reports.Report')),
            ],
        ),
    ]
