# Generated by Django 2.2.12 on 2020-05-20 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('v1', '0218_add_force_breadcrumbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchReportPage',
            fields=[
                ('cfgovpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.CFGOVPage')),
                ('process_report', models.BooleanField(default=False, help_text='If this is checked, when you press "save", the system will read in the report document and use its contents to overwrite the fields in the "Report Content" tab.<ul class="help">    <li>&bull; If you uploaded a new report file for processing, check this box.</li>    <li>&bull; If you manually edited fields in the "Report Content" tab, do not check this box</li></ul>')),
                ('preview_title', models.CharField(blank=True, max_length=255)),
                ('preview_subheading', models.CharField(blank=True, max_length=255)),
                ('preview_description', wagtail.core.fields.RichTextField(blank=True)),
                ('date_published', models.DateField(default=datetime.date.today)),
                ('report_title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('main_content', models.TextField(blank=True)),
                ('report_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'abstract': False,
            },
            bases=('v1.cfgovpage',),
        ),
    ]
