# Generated by Django 2.2.12 on 2020-06-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_reports', '0001_create_research_report_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='footnotes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportsubsection',
            name='sub_body',
            field=models.TextField(blank=True),
        ),
    ]
