# Generated by Django 2.2.13 on 2020-08-05 00:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research_reports', '0001_create_research_report_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportsubsection',
            old_name='sub_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='reportsubsection',
            old_name='sub_header',
            new_name='header',
        ),
        migrations.CreateModel(
            name='ReportSectionLevelThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('subsection', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sections_level_three', to='research_reports.ReportSubSection')),
            ],
        ),
    ]
