# Generated by Django 2.2.13 on 2020-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_reports', '0002_add_section_level_three'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchreportpage',
            name='process_report',
            field=models.BooleanField(default=False, help_text='If this is checked, when you save or publish this page, the system will read in the report document and use its contents to overwrite the fields in the "Report Content" tab.<ul class="help">    <li>&bull; If you uploaded a new report file for processing, check this box.</li>    <li>&bull; If you manually edited fields in the "Report Content" tab, do not check this box.</li></ul>'),
        ),
    ]
