# Generated by Django 2.2.12 on 2020-06-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('research_reports', '0002_report_plain_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='process_report',
            field=models.BooleanField(default=False, help_text='If this is checked, when you press "save", the system will read in the report document and use its contents to overwrite the fields in the "Report Content" tab.<ul class="help">    <li>&bull; If you uploaded a new report file for processing, check this box.</li>    <li>&bull; If you manually edited fields in the "Report Content" tab, do not check this box</li></ul>'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
