# Generated by Django 2.2.12 on 2020-06-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_reports', '0003_add_report_upload_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
