# Generated by Django 2.2.13 on 2020-07-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_reports', '0005_remove_html_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authornames',
            old_name='action',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='reportsection',
            old_name='action',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='reportsubsection',
            old_name='action',
            new_name='section',
        ),
    ]
