# Generated by Django 3.2.23 on 2023-12-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0001_squashed_0020_hourly_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ['job_category'], 'verbose_name_plural': 'Job categories'},
        ),
    ]
