# Generated by Django 3.2.12 on 2022-04-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0019_2022_squash'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblistingpage',
            name='salary_is_hourly',
            field=models.BooleanField(default=False),
        ),
    ]
