# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-23 19:14
from __future__ import unicode_literals

import modelcluster.fields
from django.db import migrations, models


def update_job_location_data(apps, schema_migration):
    JobListingPage = apps.get_model('jobmanager', 'JobListingPage')
    NewOffice = apps.get_model('jobmanager', 'NewOffice')
    NewRegion = apps.get_model('jobmanager', 'NewRegion')

    for page in JobListingPage.objects.all():
        location = page.location
        page.regions.clear()
        page.offices.clear()

        if hasattr(location, 'region'):
            region = NewRegion.objects.get(abbreviation=location.abbreviation)
            page.regions.add(region)
        else:
            office = NewOffice.objects.get(abbreviation=location.abbreviation)
            page.offices.add(office)

        page.regions.commit()
        page.offices.commit()


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0019_multiple_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblistingpage',
            name='offices',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='job_listings', to='jobmanager.NewOffice'),
        ),
        migrations.AddField(
            model_name='joblistingpage',
            name='regions',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='job_listings', to='jobmanager.NewRegion'),
        ),
        migrations.RunPython(update_job_location_data),
        migrations.RemoveField(
            model_name='joblistingpage',
            name='location',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='JobLocation',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
