# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-23 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0020_multiple_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewOffice',
            new_name='Office',
        ),
        migrations.RenameModel(
            old_name='NewRegion',
            new_name='Region',
        ),
        migrations.RenameModel(
            old_name='NewState',
            new_name='State',
        ),
    ]
