# Generated by Django 3.2.23 on 2024-01-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_research', '0001_squashed_0003_delete_conferenceregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='ap_abbr',
        ),
    ]
