# Generated by Django 3.2.12 on 2022-03-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('data_research', '0001_initial'),
        ('data_research', '0002_prep_for_deprecated_model_swapout'),
    ]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('govdelivery_code', models.CharField(max_length=250)),
                ('details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(blank=True, db_index=True, max_length=6)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CountyMortgageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(blank=True, db_index=True, max_length=6)),
                ('date', models.DateField(blank=True, db_index=True)),
                ('total', models.IntegerField(null=True)),
                ('current', models.IntegerField(null=True)),
                ('thirty', models.IntegerField(null=True)),
                ('sixty', models.IntegerField(null=True)),
                ('ninety', models.IntegerField(null=True)),
                ('other', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetroArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(blank=True, db_index=True, max_length=6)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('counties', models.JSONField(blank=True, help_text='FIPS list of counties in the MSA')),
                ('states', models.JSONField(blank=True, help_text='FIPS list of states touched by MSA')),
                ('valid', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MortgageDataConstant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, help_text='OPTIONAL SLUG', max_length=255)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, help_text='CHOOSE THE LAST MONTH OF DATA TO DISPLAY (AND SELECT THE FIRST DAY OF THAT MONTH)', null=True)),
                ('note', models.TextField(blank=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MortgageMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mortgage metadata',
                'ordering': ['name'],
            },
        ),
    ]
