# Generated by Django 3.2.13 on 2022-05-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_research', '0002_prep_for_deprecated_model_swapout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConferenceRegistration',
        ),
    ]
