# Generated by Django 3.2.12 on 2022-03-08 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('data_research', '0001_initial'),
        ('data_research', '0002_prep_for_deprecated_model_swapout'),
    ]

    dependencies = [
        ('data_research', '0003_2022_reset'),
        ('v1', '0284_2022_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgagePerformancePage',
            fields=[
                ('browsepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.browsepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('v1.browsepage',),
        ),
        migrations.CreateModel(
            name='NationalMortgageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(blank=True, db_index=True, max_length=6)),
                ('date', models.DateField(blank=True, db_index=True)),
                ('total', models.IntegerField(null=True)),
                ('current', models.IntegerField(null=True)),
                ('thirty', models.IntegerField(null=True)),
                ('sixty', models.IntegerField(null=True)),
                ('ninety', models.IntegerField(null=True)),
                ('other', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(blank=True, db_index=True, max_length=2)),
                ('name', models.CharField(blank=True, db_index=True, max_length=128)),
                ('abbr', models.CharField(max_length=2)),
                ('ap_abbr', models.CharField(help_text="The AP Stylebook's state abbreviation", max_length=20)),
                ('counties', models.JSONField(blank=True, help_text='FIPS list of counties in the state')),
                ('non_msa_counties', models.JSONField(blank=True, help_text='FIPS list of counties in the state that are not in an MSA')),
                ('msas', models.JSONField(blank=True, help_text='FIPS list of MSAs in the state')),
                ('non_msa_valid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StateMortgageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(blank=True, db_index=True, max_length=6)),
                ('date', models.DateField(blank=True, db_index=True)),
                ('total', models.IntegerField(null=True)),
                ('current', models.IntegerField(null=True)),
                ('thirty', models.IntegerField(null=True)),
                ('sixty', models.IntegerField(null=True)),
                ('ninety', models.IntegerField(null=True)),
                ('other', models.IntegerField(null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_research.state')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonMSAMortgageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(blank=True, db_index=True, max_length=6)),
                ('date', models.DateField(blank=True, db_index=True)),
                ('total', models.IntegerField(null=True)),
                ('current', models.IntegerField(null=True)),
                ('thirty', models.IntegerField(null=True)),
                ('sixty', models.IntegerField(null=True)),
                ('ninety', models.IntegerField(null=True)),
                ('other', models.IntegerField(null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_research.state')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MSAMortgageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(blank=True, db_index=True, max_length=6)),
                ('date', models.DateField(blank=True, db_index=True)),
                ('total', models.IntegerField(null=True)),
                ('current', models.IntegerField(null=True)),
                ('thirty', models.IntegerField(null=True)),
                ('sixty', models.IntegerField(null=True)),
                ('ninety', models.IntegerField(null=True)),
                ('other', models.IntegerField(null=True)),
                ('msa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_research.metroarea')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='countymortgagedata',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_research.county'),
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_research.state'),
        ),
    ]
