# Generated by Django 2.2.13 on 2020-08-10 18:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_research', '0012_recreated_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceregistration',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='metroarea',
            name='counties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='FIPS list of counties in the MSA'),
        ),
        migrations.AlterField(
            model_name='metroarea',
            name='states',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='FIPS list of states touched by MSA'),
        ),
        migrations.AlterField(
            model_name='mortgagemetadata',
            name='json_value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='counties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='FIPS list of counties in the state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='msas',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='FIPS list of MSAs in the state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='non_msa_counties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='FIPS list of counties in the state that are not in an MSA'),
        ),
    ]
