{{- if .Values.env -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cfgov.fullname" . }}
  labels:
    {{- include "cfgov.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.env | nindent 2 }}
{{- end }}
