{{- range .Values.ingress.tls }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .secretName }}
  labels:
      {{- include "cfgov.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  {{- $altNames := list ( printf "%s.%s" (include "cfgov.fullname" $) $.Release.Namespace ) ( printf "%s.%s.svc" (include "cfgov.fullname" $) $.Release.Namespace ) -}}
  {{ $cert := genSelfSignedCert ( include "cfgov.fullname" $ ) nil (concat $altNames .hosts) 365 }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end}}
