{{- if .Values.postgresql.auth.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cfgov.fullname" . }}-postgres
  labels:
    {{- include "cfgov.labels" . | nindent 4 }}
data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
  database: {{ .Values.postgresql.auth.database | b64enc }}
{{- end }}
