{{- if and (not .Values.django.existingSecretName) .Values.django.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cfgov.fullname" . }}
  labels:
    {{- include "cfgov.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.django.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
