site_name: cfgov-refresh
pages:
- Introduction: index.md
- Installation: installation.md
- Building and Deploying for cf.gov: build-and-deploy.md
- Front end guidelines:
    - Atomic structure and design: atomic-structure.md
    - Notes on adapting atomic design: notes-on-atomic-design.md
    - Notes on frameworks: notes-on-frameworks.md
theme: readthedocs

markdown_extensions:
    - admonition
    - tables
