# Generated by Django 3.2.15 on 2023-02-08 13:34

from functools import partial

from django.db import migrations


def migrate_passwordhistoryitems(apps, schema_editor, from_app=None, to_app=None):
    OldPasswordHistoryItem = apps.get_model(from_app, 'PasswordHistoryItem')
    PasswordHistoryItem = apps.get_model(to_app, 'PasswordHistoryItem')
    for obj in OldPasswordHistoryItem.objects.all():
        new_obj = PasswordHistoryItem(
            user=obj.user,
            created=obj.created,
            expires_at=obj.expires_at,
            locked_until=obj.locked_until,
            encrypted_password=obj.encrypted_password
        )
        new_obj.save()
        obj.delete()


def migrate_failedloginattempts(apps, schema_editor, from_app=None, to_app=None):
    OldFailedLoginAttempt = apps.get_model(from_app, 'FailedLoginAttempt')
    FailedLoginAttempt = apps.get_model(to_app, 'FailedLoginAttempt')
    for obj in OldFailedLoginAttempt.objects.all():
        new_obj = FailedLoginAttempt(
            user=obj.user,
            failed_attempts=obj.failed_attempts,
        )
        new_obj.save()
        obj.delete()


def migrate_temporarylockouts(apps, schema_editor, from_app=None, to_app=None):
    OldTemporaryLockout = apps.get_model(from_app, 'TemporaryLockout')
    TemporaryLockout = apps.get_model(to_app, 'TemporaryLockout')
    for obj in OldTemporaryLockout.objects.all():
        new_obj = TemporaryLockout(
            user=obj.user,
            created=obj.created,
            expires_at=obj.expires_at,
        )
        new_obj.save()
        obj.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_add_login_models'),
    ]

    operations = [
        migrations.RunPython(
            partial(migrate_passwordhistoryitems, from_app='v1', to_app='login'),
            partial(migrate_passwordhistoryitems, from_app='login', to_app='v1'),
        ),
        migrations.RunPython(
            partial(migrate_failedloginattempts, from_app='v1', to_app='login'),
            partial(migrate_failedloginattempts, from_app='login', to_app='v1'),
        ),

        migrations.RunPython(
            partial(migrate_temporarylockouts, from_app='v1', to_app='login'),
            partial(migrate_temporarylockouts, from_app='login', to_app='v1'),
        )
    ]
