# Generated by Django 3.2.18 on 2023-04-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_populate_login_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarylockout',
            name='user',
        ),
        migrations.DeleteModel(
            name='FailedLoginAttempt',
        ),
        migrations.DeleteModel(
            name='TemporaryLockout',
        ),
    ]
