# Generated by Django 3.2.18 on 2023-04-13 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_populate_login_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarylockout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passwordhistoryitem',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='passwordhistoryitem',
            name='locked_until',
        ),
        migrations.AlterField(
            model_name='passwordhistoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FailedLoginAttempt',
        ),
        migrations.DeleteModel(
            name='TemporaryLockout',
        ),
    ]
