# Generated by Django 4.2.11 on 2024-05-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_squashed_0003_simplify_password_logic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordHistoryItem",
        ),
    ]
