# Generated by Django 4.2.11 on 2024-05-20 18:18

from django.db import migrations
from django.conf import settings


def forwards(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Get the default group name for all users who need permission to log
    # into the admin, create it if necessary, and assign the
    # wagtailadmin.access_admin permission.
    group = Group.objects.get_or_create(name="Wagtail Users")[0]

    permission = Permission.objects.get(
        codename="access_admin",
        content_type=ContentType.objects.get(
            app_label="wagtailadmin", model="admin"
        ),
    )
    if not group.permissions.contains(permission):
        group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailadmin", "0001_create_admin_access_permissions"),
        ("login", "0004_delete_passwordhistoryitem"),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
