# Generated by Django 3.2.23 on 2024-03-05 18:09

from django.db import migrations, models
import tccp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tccp_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullableYearsInSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', tccp.fields.JSONListField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default=list, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='yearsinschool',
            name='years',
            field=tccp.fields.JSONListField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default=list),
        ),
    ]
