# Generated by Django 3.2.12 on 2022-03-30 17:35

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_digital_platform', '0002_alter_activitytopic_tree_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitycouncilforeconed',
            options={'verbose_name': 'National standard', 'verbose_name_plural': 'National Standards for Personal Financial Education'},
        ),
        migrations.AlterField(
            model_name='activitypage',
            name='council_for_economic_education',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='teachers_digital_platform.ActivityCouncilForEconEd', verbose_name='National Standards'),
        ),
    ]
