# Generated by Django 3.2.24 on 2024-03-12 18:00

from django.db import migrations
import v1.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_digital_platform', '0002_raw_html_affordances'),
    ]

    operations = [
        migrations.RunPython(code=migrations.RunPython.noop, reverse_code=migrations.RunPython.noop)
    ]
