# Generated by Django 3.2.14 on 2022-08-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_digital_platform', '0003_tdp_taxonomy_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypage',
            name='search_tags',
            field=models.TextField(blank=True, help_text="These words will match for the site's internal Activities search. This content will not be visible by users.", verbose_name='Activity search tags'),
        ),
    ]
