# Generated by Django 3.2.24 on 2024-03-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_digital_platform', '0003_rtf_to_urtf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityindexpage',
            name='header_sidebar',
        ),
    ]
