# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_digital_platform', '0021_activityindexpage_more_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityindexpage',
            name='cfgovpage_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.CFGOVPage'),
        ),
        migrations.AlterField(
            model_name='activitypage',
            name='cfgovpage_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.CFGOVPage'),
        ),
        migrations.AlterField(
            model_name='activitytopic',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='teachers_digital_platform.ActivityTopic'),
        ),
    ]
