# Generated by Django 3.2.5 on 2021-07-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_digital_platform', '0027_add_aria_label_to_hyperlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytopic',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='activitytopic',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='activitytopic',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
