# Generated by Django 3.2.5 on 2021-07-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_digital_platform', '0028_prep_for_django_32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysetup',
            name='card_order',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitysetup',
            name='card_setup',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitysetup',
            name='facet_setup',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
