# Generated by Django 3.2.12 on 2022-03-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('teachers_digital_platform', '0001_initial'),
        ('teachers_digital_platform', '0002_activitysubtopic'),
        ('teachers_digital_platform', '0003_auto_20180702_1507'),
        ('teachers_digital_platform', '0004_auto_20180703_0825'),
        ('teachers_digital_platform', '0005_auto_20180703_0923'),
        ('teachers_digital_platform', '0006_auto_20180704_0756'),
        ('teachers_digital_platform', '0007_auto_20180704_0907'),
        ('teachers_digital_platform', '0008_auto_20180718_1428'),
        ('teachers_digital_platform', '0009_auto_20180718_1442'),
        ('teachers_digital_platform', '0010_load_initial_data'),
        ('teachers_digital_platform', '0011_update_initial_data'),
        ('teachers_digital_platform', '0012_activitypage_handout_file_2'),
        ('teachers_digital_platform', '0013_activitybuildingblock_svg_icon'),
        ('teachers_digital_platform', '0014_update_building_blocks'),
        ('teachers_digital_platform', '0015_auto_20180816_0954'),
        ('teachers_digital_platform', '0016_auto_20180829_2323'),
        ('teachers_digital_platform', '0017_change_special_pop_to_student_chars'),
        ('teachers_digital_platform', '0018_update_student_characteristics'),
        ('teachers_digital_platform', '0019_activitybuildingblock_svg_icon_labels'),
        ('teachers_digital_platform', '0020_activityindexpage_text_introduction'),
        ('teachers_digital_platform', '0021_activityindexpage_more_editable'),
        ('teachers_digital_platform', '0022_modify_on_delete_for_django2'),
        ('teachers_digital_platform', '0023_add_activity_setup'),
        ('teachers_digital_platform', '0024_add_notification_type_option'),
        ('teachers_digital_platform', '0025_update_notification_default_type'),
        ('teachers_digital_platform', '0026_add_activity_and_handout_document'),
        ('teachers_digital_platform', '0027_add_aria_label_to_hyperlinks'),
        ('teachers_digital_platform', '0028_prep_for_django_32'),
        ('teachers_digital_platform', '0029_prep_for_deprecated_model_swapout'),
    ]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['weight', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityBloomsTaxonomyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['weight', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityBuildingBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(default=0)),
                ('svg_icon', models.CharField(blank=True, choices=[('settings', 'Executive function'), ('split', 'Financial knowledge and decision making'), ('piggy-bank-check', 'Financial habits and norms')], max_length=60, null=True)),
            ],
            options={
                'ordering': ['weight', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityCouncilForEconEd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['weight', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['weight', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityGradeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['weight', 'title'],
                'abstract': False,
            },
        ),
    ]
