# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1', '0198_recreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='HmdaHistoricDataPage',
            fields=[
                ('learnpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.LearnPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('v1.learnpage',),
        ),
    ]
