# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1', '0144_rm_hero_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='HmdaHistoricDataPage',
            fields=[
                ('browsepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.BrowsePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('v1.browsepage',),
        ),
    ]
