name: Test cfgov-apache Docker image

on:
  merge_group:
  pull_request:
    paths:
      - cfgov/apache/**
  workflow_dispatch:

jobs:
  build-and-test-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build cfgov-apache Docker image
        run: docker build cfgov/apache -t cfgov-apache:latest

      - name: Run cfgov-apache image with no proxy configured
        run: docker run -d -p 8000:8080 cfgov-apache:latest && sleep 5

      - name: Test cfgov-apache image with no proxy configured
        # Expect this to show the default Apache 404 Not Found page, since we
        # haven't configured a proxy for all web traffic.
        run: curl -s http://localhost:8000 | grep -q "404 Not Found"

      - name: Run cfgov-apache image with readonly filesystem
        # Map a writeable volume for /usr/local/apache2/logs, because that's
        # where Apache writes its pidfile. See additional notes on this in the
        # cfgov-apache Dockerfile.
        run: |
          docker volume create tmp
          docker run -d \
            -p 8001:8080 \
            --read-only \
            -v tmp:/usr/local/apache2/logs \
            cfgov-apache:latest && sleep 5

      - name: Test cfgov-apache image with readonly filesystem
        # If we didn't map a writeable volume for /usr/local/apache2/logs,
        # Apache wouldn't be able to start up successfully since it wouldn't
        # be able to write its pidfile to a readonly filesystem.
        run: curl -s http://localhost:8001 | grep -q "404 Not Found"

      - name: Run cfgov-apache image with proxy configured
        # Proxy Apache to a simulated backend using CFGOV_APPLICATION_PROXY.
        run: |
          docker network create testing
          docker run -d \
            --network testing \
            -p 8002:80 \
            --name hello \
            nginxdemos/hello:0.4
          docker run -d \
            --network testing \
            -p 8003:8080 \
            -e CFGOV_APPLICATION_PROXY=http://hello \
            cfgov-apache:latest && sleep 5

      - name: Test cfgov-apache image with proxy configured
        # Expect this to proxy to the nginxdemos/hello container.
        run: curl -sf http://localhost:8003 | grep -q "Hello World"
