name: Build cf.gov Docker images

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: cfpb/actions/docker-build-push@1ed507b96522475e6d11e5af41c55251b16f19a6
        with:
          image-name: cfgov
          token: ${{ secrets.GITHUB_TOKEN }}
