name: Build cf.gov Docker images

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: cfpb/actions/docker-build-push@14cfddeabf21df8a4960fae221b6a982e5d4f244
        with:
          image-name: cfgov
          token: ${{ secrets.GITHUB_TOKEN }}
          scan: true
          scan-mode: ${{ github.event_name == 'pull_request' && 'enforce' || 'report' }}
          scanner-client-id: ${{ secrets.WIZ_CLIENT_ID }}
          scanner-client-secret: ${{ secrets.WIZ_CLIENT_SECRET }}
