name: Maintain deployable zipfile Docker images

on:
  push:
    branches: ['main']
    paths:
      - 'docker/centos7/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    if: "! github.event.pull_request.head.repo.fork"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build deployable zipfile builder image
        run: |
          docker build docker/centos7 \
          --target=cfgov-artifact-builder \
          -t ghcr.io/cfpb/cfgov-artifact-builder:latest

      - name: Build deployable zipfile tester image
        run: |
          docker build docker/centos7 \
          --target=cfgov-artifact-tester \
          -t ghcr.io/cfpb/cfgov-artifact-tester:latest

      - name: Push deployable zipfile builder image
        run: |
          docker push ghcr.io/cfpb/cfgov-artifact-builder:latest

      - name: Push deployable zipfile tester image
        run: |
          docker push ghcr.io/cfpb/cfgov-artifact-tester:latest
