name: Deploy CF.gov to EKS
on: 
  push:
jobs: 
  build: 
    runs-on: 
      - codebuild-cfpb-cfgov-cfgov-gha-${{ github.run_id }}-${{ github.run_attempt }}

    steps: 
      - name: Checkout Friendly-Umbrella
        uses: actions/checkout@v2
    

      - name: Retrieve Security Scan Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            , ${{ secrets.SECURITY_SCAN}}
          parse-json-secrets: true
      
      - name: Build Docker Images
        run: |

          # Build the CFGOV Image
            docker build . -t ${{ secrets.CFGOV_IMAGE }}:$GITHUB_SHA

          # Build the CFGOV-Apache Image
            docker build cfgov/apache/. -t ${{ secrets.CFGOV_APACHE_IMAGE }}:$GITHUB_SHA


      - name: Security With Twistlock
        run: |
         curl -k -u "$TL_USER:$TL_PASSWORD" "$TL_CONSOLE_URL/api/v1/util/twistcli" --output twistcli
          chmod +x twistcli

         ./twistcli images scan --details -address "${TL_CONSOLE_URL}" -u  "${TL_USER}" -p "${TL_PASSWORD}" 
      

        
      # - name: Push Images to ECR
      #   run: |

      #     # Login to ECR
      #     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username ${{ secrets.AWS_USERNAME }} --password-stdin ${{ secrets.ECR_REGISTRY }}

      #     # Push to ECR
      #     docker push ${{ secrets.ECR_REPO }}:$GITHUB_SHA

      # - name: Say Hello World
      #   run: echo "Hello World"