name: functional

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://cfpb:cfpb@localhost/cfgov
      MAPBOX_ACCESS_TOKEN:  ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      DJANGO_ADMIN_USERNAME: admin
      DJANGO_ADMIN_PASSWORD: admin

    services:
      elasticsearch:
        image: elasticsearch:7.10.1
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10

      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: cfpb
          POSTGRES_PASSWORD: cfpb
          POSTGRES_DB: cfgov
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 2

    - run: corepack enable
    - name: Set up Node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
          node-version: '26.x'
          cache: yarn

    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: 3.13

    - name: Install backend dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements/local.txt

        #    - name: Get changed files
        # id: changed-files
        #uses: tj-actions/changed-files@v44.5.2
        #with:
        #separator: '___'

    - name: Set up initial data
      run: ./refresh-data.sh test.sql.gz

    - name: Prepare config
      #env:
      #  CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: ./scripts/cypress-fast-specs.sh

    - name: Cache Cypress binary
      id: cypress-cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

    - name: Install frontend dependencies
      run: yarn install --immutable --immutable-cache

    - name: Install Cypress binary
      if: steps.cypress-cache.outputs.cache-hit != 'true'
      run: npx cypress install

    - name: Verify Cypress
      run: npx cypress verify

    - name: Run Cypress
      uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v7.4.1
      with:
        install: false
        build: yarn build
        start: python cfgov/manage.py runserver 0.0.0.0:8000
        wait-on: 'http://localhost:8000'

      env:
          MAPBOX_ACCESS_TOKEN:  ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          CYPRESS_ENVIRONMENT: github
    - name: Store any Cypress failure screenshots
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: failure()
      with:
        name: cypress_failure_screenshots
        path: ./test/cypress/screenshots/
        retention-days: 1
