name: Deploy CF.gov to EKS
on: 
  push:
jobs: 
  build: 
    runs-on: 
      - codebuild-cfpb-cfgov-cfgov-gha-${{ github.run_id }}-${{ github.run_attempt }}
  steps: 
    - name: testing
      run: echo "hello from test actions"
  
    - name: testing 2
      uses: cfpb/actions/.github/workflows/image-scan.yml@v1
