name: test

# Testing.
on:
  push:
    branches:
      - veracode
  pull_request:
    branches:
      - veracode

jobs:
  Test-1:
    runs-on: [ubuntu-latest]
    steps:

# Checkout code
      - uses: actions/checkout@v4.2.2
   
      - name: Setup Veracode
        run: |
         curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: See Files
        run: |
         ls -la
      - name: zip python and javascript files 
        run: |
          zip -r cfgov-gha.zip ${{ github.workspace }}/cfgov/ ${{ github.workspace }}/package.json ${{ github.workspace }}/yarn.lock ${{ github.workspace }}/.github ${{ github.workspace }}/requirements

      - name: See Files
        run: |
         ls -la
