name: Deploy CF.gov to EKS
on: 
  push:
jobs: 
  test:
    uses: cfpb/actions/.github/workflows/image-scan.yml@main

  build: 
    runs-on: 
      - codebuild-cfpb-cfgov-cfgov-gha-${{ github.run_id }}-${{ github.run_attempt }}
    steps: 
      - name: testing
        run: echo "hello from test action!"
