name: veracode

# This workflow will checkout the code, build the app, and scan with the Veracode Static Pipeline Scanner.
on:
  push:
    branches:
      - veracode
  pull_request:
    branches:
      - veracode

jobs:
    Veracode_SAST_PR:
    runs-on: [ubuntu-latest]
    steps:
   
# Checkout code
      - uses: actions/checkout@v4

      - name: Setup Veracode
        run: |
         curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: Package App
        run: |
         ./veracode package -s . -a

    
# Download Veracode Static Pipeline Scanner     
      - name: Download Veracode Static Pipeline Scanner
        run: |
          curl https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip -o veracode.zip
          unzip -o veracode.zip
      
      - name: Run Veracode Static Pipeline Scanner
        continue-on-error: true
        run: >  
         echo ${{secrets.VERACODE_API_ID}}
         
# In this configuration, the Pipeline scanner will check against CFPB policy.
      - name: Run Veracode Static Pipeline Scanner
        continue-on-error: true
        run: >
         java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}"
         --file "./veracode-auto-pack-consumerfinance-python-no-pm.zip" --fail_on_severity="Very High, High"
         --summary_output true
        
      - id: get-comment-body
        if: ${{ github.head_ref != '' }}
        run: |
          body=$(cat results.txt)
          body="${body//$'===\n---'/'===\n<details><summary>details</summary><p>\n---'}"
          body="${body//$'---\n\n==='/'---\n</p></details>\n==='}"
          body="${body//$'\n'/'<br>'}"
          echo ::set-output name=body::$body
      - name: Add comment to PR
        if: ${{ github.head_ref != '' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          reactions: rocket    
        
# Artifact the results for later use
      - name: Archive Results.json & Results.txt from Veracode Static Pipeline Scanner
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: Pipeline Scanner Results
          path: results.*
