importDbPath: "${CFGOV_PROD_DB_LOCATION}"

env:
  ALLOW_ADMIN_URL: "True"
  APACHE_UPLOADS_F_ALIAS: "/src/consumerfinance.gov/cfgov/f/"
  MEDIA_ROOT: "/src/consumerfinance.gov/cfgov/f/"
  APACHE_STATUS_ALLOW_FROM: "127.0.0.1"
  AWS_CONFIG_FILE: /var/run/secrets/.aws/config
  AWS_SHARED_CREDENTIALS_FILE: /var/run/secrets/.aws/credentials
  AWS_PROFILE: "${AWS_PROFILE}"
  DB_DUMP_FILE: "${DB_DUMP_FILE}"
  DB_DUMP_URL: "${DB_DUMP_URL}"
  FORCE_DB_REBUILD: "${FORCE_DB_REBUILD}"
# add in desired S3 Bucket for PG_Dump
# S3_BUCKET: <enter_bucket>

django:
  secrets:
    DJANGO_ADMIN_USERNAME: "admin"
    DJANGO_ADMIN_PASSWORD: "admin"
    SECRET_KEY: "abcdefghijklmnopqrstuvwxyz"
