initContainer:
  args:
    - "bash"
    - "-c"
    - >-
      django-admin opensearch index --force rebuild &&
      django-admin opensearch document --force --refresh index

extraEnvs:
  - name: ALLOW_ADMIN_URL
    value: "True"
  - name: APACHE_UPLOADS_F_ALIAS
    value: "/src/consumerfinance.gov/cfgov/f/"
  - name: DJANGO_ADMIN_USERNAME
    value: "admin"
  - name: DJANGO_ADMIN_PASSWORD
    value: "admin"
  - name: SECRET_KEY
    value: "abcdefghijklmnopqrstuvwxyz"
  - name: MEDIA_ROOT
    value: "/src/consumerfinance.gov/cfgov/f/"
  - name: WATCHMAN_TOKENS
    value: "token"
  - name: APACHE_STATUS_ALLOW_FROM
    value: "127.0.0.1"

mapping:
  enabled: true

# If services are enabled, set service type to ClusterIP, as EKS doesn't have LoadBalancer

postgresql:
  service:
    type: ClusterIP

elasticsearch:
  service:
    type: ClusterIP

kibana:
  service:
    type: ClusterIP
