# These values are required, and always included by helm-install.sh
# Some of these values, are needed to set certain values needed between
# Sibling charts from the Parent chart (cfgov).
#
# Everything can also be overridden explicitly with --set

elasticsearch:
  # using release name to always get unique naming,
  # as elasticsearch chart breaks convention
  clusterName: "${RELEASE}-elasticsearch"

kibana:
  # match the generated elasticsearch cluster name,
  # overridable with --set kibana.elasticsearchHosts, which is useful
  # when using an external ElasticSearch host and not the Child chart
  elasticsearchHosts: "http://${RELEASE}-elasticsearch-master:9200"

# ingress is only used for local deployments
ingress:
  hosts:
    - host: ${RELEASE}.localhost  # overridable with --set ingress.hosts[0].host
      paths:
        - path: /
          pathType: ImplementationSpecific

release:
  branch: ${RELEASE_BRANCH}
  owner: ${RELEASE_OWNER}
  gitSHA: ${GitSHA}
